package com.randomjava;

import com.randomjava.lib.Difficulty;
import com.randomjava.lib.Kind;
import com.randomjava.lib.Meta;
import com.randomjava.lib.Project;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Supplier;

/**
 * GENERATED FILE - do not edit by hand.
 *
 * <p>Regenerate with {@code python3 tools/generate.py} after changing
 * {@code tools/catalog.py}.
 *
 * <p>Holds every project's metadata and a way to construct it. Both are
 * deliberately arranged so that <b>reading the catalogue does not load the
 * 251 project classes</b>.
 *
 * <p>The obvious version of this file writes {@code Foo.META} for the
 * metadata and {@code Foo::new} for the factory. Both touch the class: a
 * static field read initialises it, and a constructor reference has to link the
 * class to bootstrap its call site. Listing every project therefore loaded
 * every project, which cost about 4.7 seconds before the launcher could print
 * its menu or the hub could serve its first page - all to run one of them.
 *
 * <p>So the metadata is written out as literals, and the factories resolve
 * their class by name on first use. Starting up now touches nothing, and
 * visiting a project loads exactly that project.
 *
 * <p>The cost of the literals is that they could drift from the {@code META}
 * each project declares for itself. {@code SuiteTests} compares the two for
 * every project, which turns a silent inconsistency into a failing test.
 */
public final class Catalog {

    private Catalog() {
    }

    private static final List<Meta> ALL = List.of(
            new Meta(1, "simple-calculator", "Simple Calculator", "Beginner Friendly", Kind.TOOL, Difficulty.BEGINNER, "Evaluate an arithmetic expression with +, -, *, /, %, ^ and parentheses.", "", true),
            new Meta(2, "todo-list", "To-Do List", "Beginner Friendly", Kind.LIST, Difficulty.BEGINNER, "Keep a list of tasks you can add to, tick off and clear.", "", true),
            new Meta(3, "digital-clock", "Digital Clock", "Beginner Friendly", Kind.TOOL, Difficulty.BEGINNER, "Show the current time, with timezone and 12 or 24 hour formatting.", "", true),
            new Meta(4, "bmi-calculator", "BMI Calculator", "Beginner Friendly", Kind.TOOL, Difficulty.BEGINNER, "Work out body mass index from height and weight, in metric or imperial.", "", true),
            new Meta(5, "currency-converter", "Currency Converter", "Beginner Friendly", Kind.TOOL, Difficulty.BEGINNER, "Convert an amount between currencies using a rate table.", "", true),
            new Meta(6, "random-quote-generator", "Random Quote Generator", "Beginner Friendly", Kind.TOOL, Difficulty.BEGINNER, "Pull a random quote, optionally filtered by topic or author.", "", true),
            new Meta(7, "weather-app", "Weather App", "Beginner Friendly", Kind.TOOL, Difficulty.BEGINNER, "Look up current conditions for a city from a weather API.", "", false),
            new Meta(8, "unit-converter", "Unit Converter", "Beginner Friendly", Kind.TOOL, Difficulty.BEGINNER, "Convert length, mass, temperature, volume, speed and data sizes.", "", true),
            new Meta(9, "rock-paper-scissors", "Rock Paper Scissors", "Beginner Friendly", Kind.GAME, Difficulty.BEGINNER, "Play best-of against the computer and keep a running score.", "", true),
            new Meta(10, "countdown-timer", "Countdown Timer", "Beginner Friendly", Kind.TOOL, Difficulty.BEGINNER, "Count down from a duration and report the time remaining.", "", true),
            new Meta(11, "personal-budget-tracker", "Personal Budget Tracker", "Intermediate", Kind.LIST, Difficulty.INTERMEDIATE, "Record income and spending by category and see what is left.", "", false),
            new Meta(12, "markdown-to-html", "Markdown To HTML", "Intermediate", Kind.TOOL, Difficulty.INTERMEDIATE, "Convert Markdown text into HTML: headings, emphasis, lists, code, links.", "", true),
            new Meta(13, "chat-application", "Chat Application", "Intermediate", Kind.LIST, Difficulty.INTERMEDIATE, "Socket-backed chat with groups, friends, stored history and voice or video calls.", "", false),
            new Meta(14, "file-encryption-tool", "File Encryption Tool", "Intermediate", Kind.TOOL, Difficulty.INTERMEDIATE, "Encrypt and decrypt text or files with a passphrase-derived key.", "", false),
            new Meta(15, "recipe-finder", "Recipe Finder", "Intermediate", Kind.LIST, Difficulty.INTERMEDIATE, "Search recipes by ingredient and save the ones you like.", "", false),
            new Meta(16, "image-watermarking-tool", "Image Watermarking Tool", "Intermediate", Kind.TOOL, Difficulty.INTERMEDIATE, "Stamp text or an image watermark onto a picture.", "", false),
            new Meta(17, "expense-splitting-app", "Expense Splitting App", "Intermediate", Kind.LIST, Difficulty.INTERMEDIATE, "Split shared costs across a group and settle up with fewest transfers.", "", false),
            new Meta(18, "qr-code-generator", "QR Code Generator", "Intermediate", Kind.GRID, Difficulty.INTERMEDIATE, "Encode text as a QR matrix and render it as a grid.", "", false),
            new Meta(19, "blog-cms", "Blog CMS", "Intermediate", Kind.LIST, Difficulty.INTERMEDIATE, "Create, edit, publish and delete blog posts.", "", false),
            new Meta(20, "habit-tracker", "Habit Tracker", "Intermediate", Kind.LIST, Difficulty.INTERMEDIATE, "Track daily habits and keep streaks alive.", "", false),
            new Meta(21, "sudoku-solver", "Sudoku Solver", "Algorithms and Data Structures", Kind.GRID, Difficulty.ADVANCED, "Solve a 9x9 Sudoku with constraint-checked backtracking.", "", true),
            new Meta(22, "maze-generator", "Maze Generator", "Algorithms and Data Structures", Kind.GRID, Difficulty.INTERMEDIATE, "Carve a perfect maze with randomised depth-first search, then solve it.", "", true),
            new Meta(23, "pathfinding-visualizer", "Pathfinding Visualizer", "Algorithms and Data Structures", Kind.GRID, Difficulty.ADVANCED, "Watch A* and Dijkstra explore a weighted grid toward a goal.", "", false),
            new Meta(24, "sorting-visualizer", "Sorting Visualizer", "Algorithms and Data Structures", Kind.GRID, Difficulty.INTERMEDIATE, "Step through bubble, insertion, selection, merge and quick sort.", "", true),
            new Meta(25, "binary-search-tree-visualizer", "Binary Search Tree Visualizer", "Algorithms and Data Structures", Kind.GRID, Difficulty.ADVANCED, "Insert, delete and search in a BST and draw the shape it takes.", "", false),
            new Meta(26, "graph-traversal-simulator", "Graph Traversal Simulator", "Algorithms and Data Structures", Kind.GRID, Difficulty.INTERMEDIATE, "Run breadth-first and depth-first search over a graph, step by step.", "", false),
            new Meta(27, "anagram-finder", "Anagram Finder", "Algorithms and Data Structures", Kind.TOOL, Difficulty.BEGINNER, "Group words that are anagrams and test whether two strings match.", "", true),
            new Meta(28, "palindrome-checker", "Palindrome Checker", "Algorithms and Data Structures", Kind.TOOL, Difficulty.BEGINNER, "Test words, phrases and numbers for palindromes, ignoring punctuation.", "", true),
            new Meta(29, "prime-number-generator", "Prime Number Generator", "Algorithms and Data Structures", Kind.TOOL, Difficulty.BEGINNER, "Sieve primes up to a limit, factorise a number and test primality.", "", true),
            new Meta(30, "knapsack-solver", "Knapsack Solver", "Algorithms and Data Structures", Kind.TOOL, Difficulty.INTERMEDIATE, "Maximise value under a weight limit with dynamic programming.", "", true),
            new Meta(31, "portfolio-website", "Portfolio Website", "Web Development", Kind.LIST, Difficulty.INTERMEDIATE, "Manage the projects, skills and links that make up a portfolio page.", "", false),
            new Meta(32, "e-commerce-store", "E Commerce Store", "Web Development", Kind.LIST, Difficulty.INTERMEDIATE, "Browse and buy from a catalogue, with a cart, checkout totals, returns and stock.", "", false),
            new Meta(33, "url-shortener", "URL Shortener", "Web Development", Kind.LIST, Difficulty.INTERMEDIATE, "Mint short codes for long URLs and count the redirects.", "", true),
            new Meta(34, "polling-voting-app", "Polling Voting App", "Web Development", Kind.LIST, Difficulty.INTERMEDIATE, "Run an election: anonymous one-per-person voting, secure tallies and published results.", "", false),
            new Meta(35, "job-board", "Job Board", "Web Development", Kind.LIST, Difficulty.INTERMEDIATE, "Recruiters post openings, candidates apply and search, and applications get screened.", "", false),
            new Meta(36, "social-media-dashboard", "Social Media Dashboard", "Web Development", Kind.LIST, Difficulty.INTERMEDIATE, "Pull post metrics into one place and rank by engagement.", "", false),
            new Meta(37, "event-booking-system", "Event Booking System", "Web Development", Kind.LIST, Difficulty.INTERMEDIATE, "Hold events with limited seats and take bookings against them.", "", false),
            new Meta(38, "online-whiteboard", "Online Whiteboard", "Web Development", Kind.GRID, Difficulty.INTERMEDIATE, "A shared drawing surface you can paint, erase and clear.", "", false),
            new Meta(39, "blog-with-comments", "Blog With Comments", "Web Development", Kind.LIST, Difficulty.INTERMEDIATE, "Posts plus threaded comments with moderation.", "", false),
            new Meta(40, "newsletter-subscription", "Newsletter Subscription", "Web Development", Kind.LIST, Difficulty.INTERMEDIATE, "Collect subscribers, confirm them and handle unsubscribes.", "", false),
            new Meta(41, "fitness-tracker", "Fitness Tracker", "Mobile App Ideas", Kind.LIST, Difficulty.BEGINNER, "Log workouts, sets and distance, and total the week.", "", false),
            new Meta(42, "meditation-timer", "Meditation Timer", "Mobile App Ideas", Kind.TOOL, Difficulty.BEGINNER, "Timed sessions with interval bells and a warm-up.", "", false),
            new Meta(43, "grocery-list-app", "Grocery List App", "Mobile App Ideas", Kind.LIST, Difficulty.BEGINNER, "Shopping list grouped by aisle with quantities.", "", false),
            new Meta(44, "language-flashcards", "Language Flashcards", "Mobile App Ideas", Kind.GAME, Difficulty.BEGINNER, "Spaced-repetition flashcards that resurface what you get wrong.", "", false),
            new Meta(45, "expense-tracker", "Expense Tracker", "Mobile App Ideas", Kind.LIST, Difficulty.BEGINNER, "Log spending, tag it, and summarise by category and month.", "", true),
            new Meta(46, "mood-journal", "Mood Journal", "Mobile App Ideas", Kind.LIST, Difficulty.BEGINNER, "Record a daily mood with a note and look for patterns.", "", false),
            new Meta(47, "plant-care-reminder", "Plant Care Reminder", "Mobile App Ideas", Kind.LIST, Difficulty.BEGINNER, "Track watering schedules and flag plants that are overdue.", "", false),
            new Meta(48, "local-event-finder", "Local Event Finder", "Mobile App Ideas", Kind.LIST, Difficulty.BEGINNER, "Browse nearby events by date, distance and category.", "", false),
            new Meta(49, "parking-spot-locator", "Parking Spot Locator", "Mobile App Ideas", Kind.GRID, Difficulty.BEGINNER, "Map a car park and find the closest free bay.", "", false),
            new Meta(50, "recipe-organizer", "Recipe Organizer", "Mobile App Ideas", Kind.LIST, Difficulty.BEGINNER, "Store recipes with tags, servings and a scaled ingredient list.", "", false),
            new Meta(51, "spam-email-classifier", "Spam Email Classifier", "AI and Machine Learning", Kind.TOOL, Difficulty.ADVANCED, "Score a message as spam or not with a naive Bayes model.", "", true),
            new Meta(52, "handwritten-digit-recognizer", "Handwritten Digit Recognizer", "AI and Machine Learning", Kind.GRID, Difficulty.ADVANCED, "Draw a digit on a grid and classify it against trained templates.", "", true),
            new Meta(53, "movie-recommendation-system", "Movie Recommendation System", "AI and Machine Learning", Kind.TOOL, Difficulty.ADVANCED, "Recommend titles from ratings with collaborative filtering.", "", true),
            new Meta(54, "sentiment-analysis-tool", "Sentiment Analysis Tool", "AI and Machine Learning", Kind.TOOL, Difficulty.ADVANCED, "Rate text as positive, negative or neutral with a scored lexicon.", "", true),
            new Meta(55, "faq-chatbot", "FAQ Chatbot", "AI and Machine Learning", Kind.LIST, Difficulty.ADVANCED, "Answer questions by matching them to the closest known FAQ entry.", "", true),
            new Meta(56, "image-caption-generator", "Image Caption Generator", "AI and Machine Learning", Kind.TOOL, Difficulty.ADVANCED, "Describe an image from detected features and templates.", "", true),
            new Meta(57, "stock-price-predictor", "Stock Price Predictor", "AI and Machine Learning", Kind.TOOL, Difficulty.ADVANCED, "Project a price from history with moving averages and regression.", "", true),
            new Meta(58, "voice-command-assistant", "Voice Command Assistant", "AI and Machine Learning", Kind.LIST, Difficulty.ADVANCED, "Parse spoken or typed commands and dispatch them to handlers.", "", true),
            new Meta(59, "resume-screener", "Resume Screener", "AI and Machine Learning", Kind.TOOL, Difficulty.ADVANCED, "Score a CV against a job description by keyword and experience.", "", true),
            new Meta(60, "music-genre-classifier", "Music Genre Classifier", "AI and Machine Learning", Kind.TOOL, Difficulty.ADVANCED, "Predict a genre from tempo, energy and spectral features.", "", false),
            new Meta(61, "password-strength-checker", "Password Strength Checker", "Cybersecurity", Kind.TOOL, Difficulty.BEGINNER, "Score a password on length, variety and entropy, and explain the score.", "", true),
            new Meta(62, "secure-file-transfer", "Secure File Transfer", "Cybersecurity", Kind.TOOL, Difficulty.ADVANCED, "Move a file between hosts with encryption and an integrity check.", "", true),
            new Meta(63, "port-scanner", "Port Scanner", "Cybersecurity", Kind.LIST, Difficulty.ADVANCED, "Probe this machine for open TCP ports and name the usual services.", "", true),
            new Meta(64, "keylogger-detector", "Keylogger Detector", "Cybersecurity", Kind.LIST, Difficulty.ADVANCED, "Flag processes and hooks that look like they are capturing keystrokes.", "", true),
            new Meta(65, "two-factor-authentication", "Two Factor Authentication", "Cybersecurity", Kind.TOOL, Difficulty.INTERMEDIATE, "Generate and verify time-based one-time passwords.", "", true),
            new Meta(66, "encrypted-chat-app", "Encrypted Chat App", "Cybersecurity", Kind.LIST, Difficulty.ADVANCED, "Chat where every message is encrypted before it leaves the client.", "", true),
            new Meta(67, "honeypot-server", "Honeypot Server", "Cybersecurity", Kind.LIST, Difficulty.ADVANCED, "Fake service that logs everything an intruder tries.", "", true),
            new Meta(68, "brute-force-simulator", "Brute Force Simulator", "Cybersecurity", Kind.TOOL, Difficulty.BEGINNER, "Estimate how long a password survives a given attack rate.", "", true),
            new Meta(69, "secure-note-taking-app", "Secure Note-Taking App", "Cybersecurity", Kind.LIST, Difficulty.ADVANCED, "Notes and saved passwords, encrypted at rest behind one master password.", "", true),
            new Meta(70, "digital-signature-generator", "Digital Signature Generator", "Cybersecurity", Kind.TOOL, Difficulty.ADVANCED, "Sign a message with a private key and verify it with the public one.", "", true),
            new Meta(71, "snake", "Snake", "Game Development", Kind.GRID, Difficulty.INTERMEDIATE, "Steer a growing snake around a board without hitting anything.", "", true),
            new Meta(72, "tetris", "Tetris", "Game Development", Kind.GRID, Difficulty.INTERMEDIATE, "Falling tetrominoes you rotate and drop to clear lines.", "", true),
            new Meta(73, "memory-matching-game", "Memory Matching Game", "Game Development", Kind.GRID, Difficulty.BEGINNER, "Flip cards two at a time and remember where the pairs are.", "", true),
            new Meta(74, "platformer-2d", "Platformer 2D", "Game Development", Kind.GRID, Difficulty.ADVANCED, "Run and jump across a tile map with gravity and collisions.", "", true),
            new Meta(75, "chess-engine", "Chess Engine", "Game Development", Kind.GRID, Difficulty.ADVANCED, "Legal move generation and a minimax search with alpha-beta pruning.", "", true),
            new Meta(76, "multiplayer-trivia", "Multiplayer Trivia", "Game Development", Kind.GAME, Difficulty.INTERMEDIATE, "Timed questions with several players racing to answer.", "", true),
            new Meta(77, "space-shooter", "Space Shooter", "Game Development", Kind.GRID, Difficulty.INTERMEDIATE, "Dodge and shoot waves of descending enemies.", "", true),
            new Meta(78, "word-scramble", "Word Scramble", "Game Development", Kind.GAME, Difficulty.BEGINNER, "Unscramble a shuffled word against the clock.", "", true),
            new Meta(79, "virtual-pet", "Virtual Pet", "Game Development", Kind.GAME, Difficulty.BEGINNER, "Feed, play with and rest a pet whose stats decay over time.", "", true),
            new Meta(80, "tower-defense", "Tower Defense", "Game Development", Kind.GRID, Difficulty.ADVANCED, "Place towers along a path and stop waves of creeps.", "", true),
            new Meta(81, "covid-data-dashboard", "Covid Data Dashboard", "Data Science", Kind.TOOL, Difficulty.INTERMEDIATE, "Summarise case and vaccination series by region and date.", "", true),
            new Meta(82, "sales-forecasting", "Sales Forecasting", "Data Science", Kind.TOOL, Difficulty.INTERMEDIATE, "Forecast next period from trend and seasonality.", "", true),
            new Meta(83, "box-office-predictor", "Box Office Predictor", "Data Science", Kind.TOOL, Difficulty.INTERMEDIATE, "Predict opening weekend from budget, genre and screen count.", "", true),
            new Meta(84, "customer-churn-analysis", "Customer Churn Analysis", "Data Science", Kind.TOOL, Difficulty.INTERMEDIATE, "Score which customers are likely to leave and why.", "", true),
            new Meta(85, "traffic-analysis", "Traffic Analysis", "Data Science", Kind.TOOL, Difficulty.INTERMEDIATE, "Aggregate sensor counts into flow, density and congestion.", "", true),
            new Meta(86, "air-quality-monitor", "Air Quality Monitor", "Data Science", Kind.TOOL, Difficulty.INTERMEDIATE, "Turn pollutant readings into an AQI band and health advice.", "", true),
            new Meta(87, "crypto-price-tracker", "Crypto Price Tracker", "Data Science", Kind.LIST, Difficulty.INTERMEDIATE, "Watch a basket of coins and alert on percentage moves.", "", true),
            new Meta(88, "sports-statistics-analyzer", "Sports Statistics Analyzer", "Data Science", Kind.TOOL, Difficulty.INTERMEDIATE, "Compute per-game and efficiency stats and rank players.", "", true),
            new Meta(89, "weather-pattern-predictor", "Weather Pattern Predictor", "Data Science", Kind.TOOL, Difficulty.INTERMEDIATE, "Find seasonal patterns in historical weather and extrapolate.", "", true),
            new Meta(90, "energy-consumption-dashboard", "Energy Consumption Dashboard", "Data Science", Kind.TOOL, Difficulty.INTERMEDIATE, "Break down usage by appliance and hour, and cost it.", "", true),
            new Meta(91, "file-organizer", "File Organizer", "Automation and Tools", Kind.TOOL, Difficulty.BEGINNER, "Sort a folder into subfolders by type, date or rules.", "", true),
            new Meta(92, "email-automation-bot", "Email Automation Bot", "Automation and Tools", Kind.LIST, Difficulty.BEGINNER, "Queue templated emails and send them on a schedule.", "", true),
            new Meta(93, "news-web-scraper", "News Web Scraper", "Automation and Tools", Kind.LIST, Difficulty.BEGINNER, "Pull headlines from sources and de-duplicate them.", "", true),
            new Meta(94, "pdf-merger-splitter", "PDF Merger Splitter", "Automation and Tools", Kind.TOOL, Difficulty.BEGINNER, "Merge PDFs, split by page range and reorder pages.", "", true),
            new Meta(95, "auto-image-resizer", "Auto Image Resizer", "Automation and Tools", Kind.TOOL, Difficulty.BEGINNER, "Batch resize to target dimensions while keeping aspect ratio.", "", true),
            new Meta(96, "invoice-generator", "Invoice Generator", "Automation and Tools", Kind.LIST, Difficulty.BEGINNER, "Build line items into a numbered invoice with tax and totals.", "", true),
            new Meta(97, "backup-automation", "Backup Automation", "Automation and Tools", Kind.TOOL, Difficulty.BEGINNER, "Copy a source tree to a destination, skipping unchanged files.", "", true),
            new Meta(98, "social-post-scheduler", "Social Post Scheduler", "Automation and Tools", Kind.LIST, Difficulty.BEGINNER, "Queue posts per platform and dispatch them at the right time.", "", true),
            new Meta(99, "data-cleaning-script", "Data Cleaning Script", "Automation and Tools", Kind.TOOL, Difficulty.BEGINNER, "Trim, de-duplicate, fix types and fill gaps in a table.", "", true),
            new Meta(100, "auto-form-filler", "Auto Form Filler", "Automation and Tools", Kind.LIST, Difficulty.BEGINNER, "Store field profiles and apply them to a form definition.", "", true),
            new Meta(101, "ascii-art-generator", "ASCII Art Generator", "Creative and Fun", Kind.GRID, Difficulty.BEGINNER, "Turn text into a large ASCII banner using a built-in block font.", "", true),
            new Meta(102, "meme-generator", "Meme Generator", "Creative and Fun", Kind.TOOL, Difficulty.BEGINNER, "Lay top and bottom captions over a template image.", "", false),
            new Meta(103, "music-visualizer", "Music Visualizer", "Creative and Fun", Kind.GRID, Difficulty.INTERMEDIATE, "Animate frequency bands from an audio signal.", "", false),
            new Meta(104, "random-story-generator", "Random Story Generator", "Creative and Fun", Kind.TOOL, Difficulty.BEGINNER, "Assemble a story from grammar rules and a word bank.", "", false),
            new Meta(105, "pixel-art-editor", "Pixel Art Editor", "Creative and Fun", Kind.GRID, Difficulty.INTERMEDIATE, "Paint on a pixel canvas with a palette and export the result.", "", false),
            new Meta(106, "virtual-art-gallery", "Virtual Art Gallery", "Creative and Fun", Kind.LIST, Difficulty.BEGINNER, "Curate rooms of works with artist, year and description.", "", false),
            new Meta(107, "interactive-map", "Interactive Map", "Creative and Fun", Kind.GRID, Difficulty.INTERMEDIATE, "Place and inspect markers on a pannable tile map.", "", false),
            new Meta(108, "horoscope-app", "Horoscope App", "Creative and Fun", Kind.TOOL, Difficulty.BEGINNER, "Give a daily reading for a sign worked out from a birth date.", "", false),
            new Meta(109, "poetry-generator", "Poetry Generator", "Creative and Fun", Kind.TOOL, Difficulty.BEGINNER, "Write verse to a chosen form, counting syllables and rhyme.", "", false),
            new Meta(110, "animated-greeting-card", "Animated Greeting Card", "Creative and Fun", Kind.TOOL, Difficulty.BEGINNER, "Build a personalised card with a message and an animation.", "", false),
            new Meta(111, "volunteer-matching", "Volunteer Matching", "Community and Social Good", Kind.LIST, Difficulty.INTERMEDIATE, "Match volunteers to opportunities by skill and availability.", "", false),
            new Meta(112, "donation-tracker", "Donation Tracker", "Community and Social Good", Kind.LIST, Difficulty.INTERMEDIATE, "Track donations against a goal and thank donors.", "", false),
            new Meta(113, "disaster-relief-coordination", "Disaster Relief Coordination", "Community and Social Good", Kind.LIST, Difficulty.INTERMEDIATE, "Report incidents, match needs to offers by location and urgency, and track recovery.", "", false),
            new Meta(114, "blood-donation-finder", "Blood Donation Finder", "Community and Social Good", Kind.LIST, Difficulty.INTERMEDIATE, "Find compatible donors and drives near a location.", "", true),
            new Meta(115, "food-waste-reduction", "Food Waste Reduction", "Community and Social Good", Kind.LIST, Difficulty.INTERMEDIATE, "Surface surplus food before it expires and route it to takers.", "", false),
            new Meta(116, "accessibility-checker", "Accessibility Checker", "Community and Social Good", Kind.TOOL, Difficulty.BEGINNER, "Audit markup for contrast, alt text, labels and heading order.", "", true),
            new Meta(117, "mental-health-support-chatbot", "Mental Health Support Chatbot", "Community and Social Good", Kind.LIST, Difficulty.INTERMEDIATE, "Reflective prompts, grounding exercises and signposting to real help.", "", false),
            new Meta(118, "public-transport-tracker", "Public Transport Tracker", "Community and Social Good", Kind.LIST, Difficulty.INTERMEDIATE, "Next departures for a stop with delays and alerts.", "", false),
            new Meta(119, "missing-persons-database", "Missing Persons Database", "Community and Social Good", Kind.LIST, Difficulty.INTERMEDIATE, "Searchable records with descriptions, last seen and case status.", "", false),
            new Meta(120, "community-garden-planner", "Community Garden Planner", "Community and Social Good", Kind.GRID, Difficulty.INTERMEDIATE, "Lay out plots and plan what goes in each bed by season.", "", false),
            new Meta(121, "blockchain-voting", "Blockchain Voting", "Advanced and Experimental", Kind.LIST, Difficulty.ADVANCED, "Cast votes into a hash-linked chain that can be independently verified.", "", true),
            new Meta(122, "decentralized-file-storage", "Decentralized File Storage", "Advanced and Experimental", Kind.LIST, Difficulty.ADVANCED, "Shard a file across nodes with redundancy and content addressing.", "", true),
            new Meta(123, "iot-home-automation", "IoT Home Automation", "Advanced and Experimental", Kind.LIST, Difficulty.ADVANCED, "Devices, sensor readings and rules that act on them.", "", false),
            new Meta(124, "drone-control-interface", "Drone Control Interface", "Advanced and Experimental", Kind.GRID, Difficulty.ADVANCED, "Plan a waypoint mission and watch telemetry against it.", "", false),
            new Meta(125, "ar-navigation", "AR Navigation", "Advanced and Experimental", Kind.TOOL, Difficulty.ADVANCED, "Turn a route into bearing and distance cues for an AR overlay.", "", false),
            new Meta(126, "vr-museum-tour", "VR Museum Tour", "Advanced and Experimental", Kind.LIST, Difficulty.ADVANCED, "Rooms, exhibits and a guided path through a virtual museum.", "", false),
            new Meta(127, "ai-code-reviewer", "AI Code Reviewer", "Advanced and Experimental", Kind.TOOL, Difficulty.ADVANCED, "Flag smells, risky patterns and style problems in a snippet.", "", false),
            new Meta(128, "smart-traffic-light", "Smart Traffic Light", "Advanced and Experimental", Kind.GRID, Difficulty.ADVANCED, "Simulate a junction: lights, routes and signal timing that adapts to the queues waiting.", "", false),
            new Meta(129, "number-guessing-game", "Number Guessing Game", "Core Java and Games", Kind.GAME, Difficulty.BEGINNER, "Guess a hidden number in a range, with higher or lower feedback and limited attempts.", "Core Java, JavaFX", false),
            new Meta(130, "tic-tac-toe", "Tic-Tac-Toe", "Core Java and Games", Kind.GAME, Difficulty.BEGINNER, "Noughts and crosses against a friend or an unbeatable minimax computer.", "Core Java, JavaFX, 2D arrays", true),
            new Meta(131, "word-counter", "Word Counter", "Core Java and Games", Kind.TOOL, Difficulty.BEGINNER, "Count words, characters, sentences, paragraphs and reading time in a block of text.", "Core Java, JavaFX, string manipulation", true),
            new Meta(132, "text-based-adventure", "Text Based Adventure", "Core Java and Games", Kind.GAME, Difficulty.BEGINNER, "Navigate rooms by typing commands, carrying an inventory and saving progress.", "Core Java, Java Collections, file I/O", false),
            new Meta(133, "simple-banking-app", "Simple Banking App", "Core Java and Games", Kind.LIST, Difficulty.BEGINNER, "Open accounts and make deposits, withdrawals and balance enquiries with a transaction log.", "Core Java, JavaFX, file handling, Collections", false),
            new Meta(134, "scientific-calculator", "Scientific Calculator", "Core Java and Games", Kind.TOOL, Difficulty.INTERMEDIATE, "Trigonometry, logarithms, roots and powers on top of the usual arithmetic.", "Core Java, JavaFX, Java math libraries", false),
            new Meta(135, "text-editor", "Text Editor", "Core Java and Games", Kind.TOOL, Difficulty.ADVANCED, "Open, edit and save text files with cut, copy, paste and undo.", "Core Java, JavaFX, file I/O", false),
            new Meta(136, "brick-breaker", "Brick Breaker", "Core Java and Games", Kind.GRID, Difficulty.BEGINNER, "Bounce a ball off a paddle to clear a wall of bricks, tracking score and lives.", "Core Java, JavaFX, 2D graphics and event handling", false),
            new Meta(137, "flappy-bird", "Flappy Bird", "Core Java and Games", Kind.GRID, Difficulty.INTERMEDIATE, "Tap to keep a bird airborne through gaps in scrolling pipes.", "Core Java, JavaFX, animation and collision detection", false),
            new Meta(138, "color-hunt-game", "Color Hunt Game", "Core Java and Games", Kind.GAME, Difficulty.INTERMEDIATE, "Name the colour a word is printed in, not the word itself, against the clock.", "Core Java, JavaFX, timers and event handling", false),
            new Meta(139, "digital-steganography", "Digital Steganography", "Core Java and Games", Kind.TOOL, Difficulty.ADVANCED, "Hide a message in the low bits of an image and pull it back out again.", "Core Java, JavaFX, Java Image I/O, encryption libraries, MySQL", false),
            new Meta(140, "attendance-management", "Attendance Management", "School and Campus Systems", Kind.LIST, Difficulty.BEGINNER, "Record attendance per session and report totals and percentages per person.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(141, "library-management", "Library Management", "School and Campus Systems", Kind.LIST, Difficulty.BEGINNER, "Issue and return books, track due dates and calculate overdue fines.", "Spring Boot, MySQL, Hibernate, Thymeleaf, Spring Security", false),
            new Meta(142, "grading-system", "Grading System", "School and Campus Systems", Kind.LIST, Difficulty.BEGINNER, "Enter marks per subject, then compute averages, grades and class rank.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(143, "school-management", "School Management", "School and Campus Systems", Kind.LIST, Difficulty.BEGINNER, "Records for students, teachers and staff with role-based views.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(144, "cgpa-calculator", "CGPA Calculator", "School and Campus Systems", Kind.TOOL, Difficulty.INTERMEDIATE, "Turn per-semester credits and grades into an SGPA and a cumulative CGPA.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(145, "exam-seating-arrangement", "Exam Seating Arrangement", "School and Campus Systems", Kind.GRID, Difficulty.INTERMEDIATE, "Lay students out across halls so no two from the same subject sit adjacent.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(146, "atm-simulation", "ATM Simulation", "Business and Records Systems", Kind.LIST, Difficulty.BEGINNER, "PIN entry, then deposits, withdrawals with note breakdown, and a statement.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(147, "pharmacy-management", "Pharmacy Management", "Business and Records Systems", Kind.LIST, Difficulty.BEGINNER, "Stock, expiry dates and dispensing, flagging medicines that are running out.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(148, "supermarket-billing", "Supermarket Billing", "Business and Records Systems", Kind.LIST, Difficulty.BEGINNER, "Scan items into a basket and produce an itemised bill with tax and discounts.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(149, "supply-chain-management", "Supply Chain Management", "Business and Records Systems", Kind.LIST, Difficulty.BEGINNER, "Track inventory and orders from supplier to customer with stock levels.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(150, "helpdesk-management", "Helpdesk Management", "Business and Records Systems", Kind.LIST, Difficulty.BEGINNER, "Raise tickets, assign them, track status and measure time to resolution.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(151, "online-quiz-management", "Online Quiz Management", "Business and Records Systems", Kind.LIST, Difficulty.BEGINNER, "Build quizzes, sit them under a time limit and review the marked answers.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(152, "crime-records-management", "Crime Records Management", "Business and Records Systems", Kind.LIST, Difficulty.INTERMEDIATE, "File reports and complaints, link them to cases and search the record.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(153, "criminal-face-detection", "Criminal Face Detection", "Business and Records Systems", Kind.TOOL, Difficulty.ADVANCED, "Match a face against a database of records and return the closest candidates.", "Core Java, OpenCV, DeepLearning4J, MySQL, JavaFX", false),
            new Meta(154, "bug-tracking-system", "Bug Tracking System", "Business and Records Systems", Kind.LIST, Difficulty.ADVANCED, "Log defects with severity and status, assign them and follow them to closure.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(155, "customer-relationship-manager", "Customer Relationship Manager", "Business and Records Systems", Kind.LIST, Difficulty.ADVANCED, "Customers, the interactions you have had with them, and the deals in flight.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(156, "id-card-generator", "ID Card Generator", "Business and Records Systems", Kind.TOOL, Difficulty.INTERMEDIATE, "Turn a person's details into a printable ID card with a photo and barcode.", "Spring Boot, MySQL, Thymeleaf, iText, Spring Security", false),
            new Meta(157, "cv-resume-builder", "CV Resume Builder", "Business and Records Systems", Kind.TOOL, Difficulty.INTERMEDIATE, "Collect career details and lay them out into a formatted, exportable CV.", "Spring Boot, MySQL, Thymeleaf, iText, Spring Security", false),
            new Meta(158, "airline-reservation", "Airline Reservation", "Travel, City and Communication", Kind.LIST, Difficulty.BEGINNER, "Search flights, pick seats, book and cancel, with live seat availability.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(159, "smart-city-guide", "Smart City Guide", "Travel, City and Communication", Kind.LIST, Difficulty.BEGINNER, "Hotels, restaurants and attractions for a city, searchable by category.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(160, "online-cab-booking", "Online Cab Booking", "Travel, City and Communication", Kind.LIST, Difficulty.INTERMEDIATE, "Book a cab between two points with fare and arrival estimates and trip status.", "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate", false),
            new Meta(161, "simple-search-engine", "Simple Search Engine", "Travel, City and Communication", Kind.TOOL, Difficulty.INTERMEDIATE, "Index documents and rank results for a query by term frequency.", "Spring Boot, MySQL, Apache Lucene, Thymeleaf, Spring Security", false),
            new Meta(162, "social-networking-site", "Social Networking Site", "Travel, City and Communication", Kind.LIST, Difficulty.ADVANCED, "Profiles, posts, follows and a timeline assembled from who you follow.", "Spring Boot, MySQL, Thymeleaf, Spring Security, WebSocket", false),
            new Meta(163, "email-system", "Email System", "Travel, City and Communication", Kind.LIST, Difficulty.ADVANCED, "Compose, send, receive and thread messages into folders.", "Spring Boot, JavaMail API, MySQL, Thymeleaf, Spring Security", false),
            new Meta(164, "office-vpn", "Office VPN", "Travel, City and Communication", Kind.TOOL, Difficulty.INTERMEDIATE, "Tunnel traffic between two hosts over an encrypted socket connection.", "Core Java, Java sockets, MySQL, JavaFX, Java security libraries", false),
            new Meta(165, "rubiks-cube-3x3", "Rubiks Cube 3x3", "Twisty Puzzles", Kind.GRID, Difficulty.ADVANCED, "Scramble it, solve it with every move explained, ask for one hint, or type in your own cube.", "", true),
            new Meta(166, "pocket-cube-2x2", "Pocket Cube 2x2", "Twisty Puzzles", Kind.GRID, Difficulty.INTERMEDIATE, "Solved in the fewest turns possible, by measuring the whole puzzle and walking downhill.", "", true),
            new Meta(167, "revenge-cube-4x4", "Revenge Cube 4x4", "Twisty Puzzles", Kind.GRID, Difficulty.ADVANCED, "Four layers: pair the centres and the edges, then finish it as a 3x3.", "", true),
            new Meta(168, "professor-cube-5x5", "Professor Cube 5x5", "Twisty Puzzles", Kind.GRID, Difficulty.ADVANCED, "Five layers, with a fixed centre again but three-piece edges to build.", "", true),
            new Meta(169, "v-cube-6x6", "V Cube 6x6", "Twisty Puzzles", Kind.GRID, Difficulty.ADVANCED, "Six layers. Reduction on a bigger scale, with inner slices and parity to handle.", "", true),
            new Meta(170, "v-cube-7x7", "V Cube 7x7", "Twisty Puzzles", Kind.GRID, Difficulty.ADVANCED, "Seven layers, the largest mass-produced cube, solved by the same reduction idea.", "", true),
            new Meta(171, "void-cube", "Void Cube", "Twisty Puzzles", Kind.GRID, Difficulty.ADVANCED, "A 3x3 with the centres removed, so there is no fixed frame to solve against.", "", true),
            new Meta(172, "mirror-cube", "Mirror Cube", "Twisty Puzzles", Kind.GRID, Difficulty.ADVANCED, "A 3x3 in one colour where the pieces are different sizes, so shape is the only clue.", "", true),
            new Meta(173, "axis-cube", "Axis Cube", "Twisty Puzzles", Kind.GRID, Difficulty.ADVANCED, "A 3x3 cut at an angle, so turning it changes its shape entirely before it comes back.", "", true),
            new Meta(174, "pyraminx", "Pyraminx", "Twisty Puzzles", Kind.GRID, Difficulty.INTERMEDIATE, "A tetrahedron with four trivial tips and only four real turning axes.", "", false),
            new Meta(175, "skewb", "Skewb", "Twisty Puzzles", Kind.GRID, Difficulty.INTERMEDIATE, "Turns on its corners rather than its faces, cutting the cube along diagonals.", "", false),
            new Meta(176, "megaminx", "Megaminx", "Twisty Puzzles", Kind.GRID, Difficulty.ADVANCED, "A dodecahedron: twelve faces, fifty pieces, solved layer by layer like a 3x3.", "", false),
            new Meta(177, "square-1", "Square 1", "Twisty Puzzles", Kind.GRID, Difficulty.ADVANCED, "Changes shape as it turns, so the first job is getting it back to a cube.", "", false),
            new Meta(178, "rubiks-clock", "Rubiks Clock", "Twisty Puzzles", Kind.GRID, Difficulty.INTERMEDIATE, "Nine dials on each side, driven by four pins. No twisting at all, pure logic.", "", false),
            new Meta(179, "pyramorphix", "Pyramorphix", "Twisty Puzzles", Kind.GRID, Difficulty.INTERMEDIATE, "A 2x2 in a tetrahedron shell, so it deforms as you turn it.", "", true),
            new Meta(180, "gear-cube", "Gear Cube", "Twisty Puzzles", Kind.GRID, Difficulty.INTERMEDIATE, "Every turn drives gears that rotate the edges, so faces only move in half turns.", "", false),
            new Meta(181, "dino-cube", "Dino Cube", "Twisty Puzzles", Kind.GRID, Difficulty.BEGINNER, "Twelve edge pieces turning around the corners. No corners or centres to worry about.", "", false),
            new Meta(182, "floppy-cube", "Floppy Cube", "Twisty Puzzles", Kind.GRID, Difficulty.BEGINNER, "A single 1x3x3 layer. Small enough that every position can be listed exhaustively.", "", false),
            new Meta(183, "cfop-trainer", "CFOP Trainer", "Cube Solving Methods", Kind.LIST, Difficulty.ADVANCED, "Drill the last-layer cases: recognise the pattern, recall the algorithm.", "", true),
            new Meta(184, "method-comparison", "Method Comparison", "Cube Solving Methods", Kind.TOOL, Difficulty.ADVANCED, "Run layer-by-layer and CFOP on the same scramble and compare the move counts.", "", true),
            new Meta(185, "speedcube-timer", "Speedcube Timer", "Cube Solving Methods", Kind.LIST, Difficulty.BEGINNER, "Inspection countdown, timing, and rolling averages of 5 and 12 over a session.", "", true),
            new Meta(186, "cube-1x1x1", "Cube 1x1x1", "Big Cubes", Kind.GRID, Difficulty.BEGINNER, "A single cubie with nothing to turn, so it is solved the moment you pick it up.", "", true),
            new Meta(187, "cube-8x8x8", "Cube 8x8x8", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Eight layers. Past the official limit, and heavy enough to be awkward.", "", true),
            new Meta(188, "cube-9x9x9", "Cube 9x9x9", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Nine layers, the first odd cube beyond official competition sizes.", "", true),
            new Meta(189, "cube-10x10x10", "Cube 10x10x10", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Ten layers, where lockups start to matter as much as method.", "", true),
            new Meta(190, "cube-11x11x11", "Cube 11x11x11", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Eleven layers. Often demonstrated rather than raced.", "", true),
            new Meta(191, "cube-12x12x12", "Cube 12x12x12", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Twelve layers of reduction before a 3x3 is left underneath.", "", true),
            new Meta(192, "cube-13x13x13", "Cube 13x13x13", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Thirteen layers, near the mechanical limit of the classic design.", "", true),
            new Meta(193, "cube-14x14x14", "Cube 14x14x14", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Fourteen layers, a collector's cube more than a solver's.", "", true),
            new Meta(194, "cube-15x15x15", "Cube 15x15x15", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Fifteen layers, with well over a thousand stickers to track.", "", true),
            new Meta(195, "cube-16x16x16", "Cube 16x16x16", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Sixteen layers, even-numbered so parity comes with it.", "", true),
            new Meta(196, "cube-17x17x17", "Cube 17x17x17", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Seventeen layers. The Over The Top cube, long the largest made.", "", true),
            new Meta(197, "cube-19x19x19", "Cube 19x19x19", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Nineteen layers, deep into exhibition territory.", "", true),
            new Meta(198, "cube-21x21x21", "Cube 21x21x21", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Twenty-one layers, frequently cited as the largest you can buy.", "", true),
            new Meta(199, "cube-22x22x22", "Cube 22x22x22", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Twenty-two layers, firmly experimental.", "", true),
            new Meta(200, "cube-23x23x23", "Cube 23x23x23", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Twenty-three layers, with centres that take longer than most whole solves.", "", true),
            new Meta(201, "cube-25x25x25", "Cube 25x25x25", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Twenty-five layers, 3,750 stickers of reduction.", "", true),
            new Meta(202, "cube-28x28x28", "Cube 28x28x28", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Twenty-eight layers, an even cube at experimental scale.", "", true),
            new Meta(203, "cube-29x29x29", "Cube 29x29x29", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Twenty-nine layers of patience.", "", true),
            new Meta(204, "cube-33x33x33", "Cube 33x33x33", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Thirty-three layers. Gregoire Pfennig's build, over 6,000 pieces.", "", true),
            new Meta(205, "cube-34x34x34", "Cube 34x34x34", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Thirty-four layers, beyond any practical solve.", "", true),
            new Meta(206, "cube-35x35x35", "Cube 35x35x35", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Thirty-five layers, mostly a demonstration that it can exist.", "", true),
            new Meta(207, "cube-49x49x49", "Cube 49x49x49", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "Forty-nine layers. Preston Alden's build, 13,839 pieces and 65 pounds.", "", true),
            new Meta(208, "cube-100x100x100", "Cube 100x100x100", "Big Cubes", Kind.GRID, Difficulty.ADVANCED, "One hundred layers and 60,000 stickers, the largest cube ever built.", "", true),
            new Meta(209, "fisher-cube", "Fisher Cube", "Shape Modifications", Kind.GRID, Difficulty.ADVANCED, "A 3x3 turned 45 degrees about one axis, so edges and centres swap roles.", "", true),
            new Meta(210, "windmill-cube", "Windmill Cube", "Shape Modifications", Kind.GRID, Difficulty.ADVANCED, "A 3x3 with the middle layer tilted, giving it a windmill silhouette.", "", true),
            new Meta(211, "ghost-cube", "Ghost Cube", "Shape Modifications", Kind.GRID, Difficulty.ADVANCED, "A 3x3 where no two pieces are alike, so only shape tells you anything.", "", true),
            new Meta(212, "mastermorphix", "Mastermorphix", "Shape Modifications", Kind.GRID, Difficulty.ADVANCED, "A 3x3 reshaped into a tetrahedron, with centres that visibly rotate.", "", true),
            new Meta(213, "bandaged-cube", "Bandaged Cube", "Shape Modifications", Kind.GRID, Difficulty.ADVANCED, "A 3x3 with pieces glued together, so many turns are simply blocked.", "", true),
            new Meta(214, "dreidel-cube", "Dreidel Cube", "Shape Modifications", Kind.GRID, Difficulty.ADVANCED, "A 3x3 with extra corner cuts, shaped like a spinning top.", "", true),
            new Meta(215, "x-cube", "X Cube", "Shape Modifications", Kind.GRID, Difficulty.ADVANCED, "A 3x3 with X-shaped cuts that extend past the faces.", "", true),
            new Meta(216, "bump-cube", "Bump Cube", "Shape Modifications", Kind.GRID, Difficulty.ADVANCED, "A mirror cube by another name: one colour, pieces of differing height.", "", true),
            new Meta(217, "camouflage-cube", "Camouflage Cube", "Shape Modifications", Kind.GRID, Difficulty.ADVANCED, "A 3x3 with offset layers, so a solved cube looks scrambled.", "", true),
            new Meta(218, "truncated-cube", "Truncated Cube", "Shape Modifications", Kind.GRID, Difficulty.ADVANCED, "A 3x3 with its corners sliced off, changing the look and nothing else.", "", true),
            new Meta(219, "cylindrical-cube", "Cylindrical Cube", "Shape Modifications", Kind.GRID, Difficulty.ADVANCED, "A 3x3 turned into a cylinder. The gentlest shape mod there is.", "", true),
            new Meta(220, "windmill-morphix", "Windmill Morphix", "Shape Modifications", Kind.GRID, Difficulty.ADVANCED, "A windmill cube and a mastermorphix crossed, shifting shape twice over.", "", true),
            new Meta(221, "junior-cube", "Junior Cube", "Shape Modifications", Kind.GRID, Difficulty.ADVANCED, "A 2x2 sold for children. Corners only, and every state within eleven turns.", "", true),
            new Meta(222, "tower-of-hanoi", "Tower Of Hanoi", "Logic and Puzzle Games", Kind.GRID, Difficulty.BEGINNER, "Move a stack of discs between three pegs, never putting a larger disc on a smaller.", "", true),
            new Meta(223, "n-queens", "N Queens", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Place N queens on a board so that no two of them attack each other.", "", true),
            new Meta(224, "sliding-15-puzzle", "Sliding 15 Puzzle", "Logic and Puzzle Games", Kind.GRID, Difficulty.BEGINNER, "Slide numbered tiles into order through the one empty square.", "", true),
            new Meta(225, "minesweeper", "Minesweeper", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Clear a grid without detonating a mine, using the counts as clues.", "", true),
            new Meta(226, "game-2048", "Game 2048", "Logic and Puzzle Games", Kind.GRID, Difficulty.BEGINNER, "Slide and merge matching tiles, doubling each time, to reach 2048.", "", true),
            new Meta(227, "sokoban", "Sokoban", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Push crates onto targets in a warehouse, never pulling and never squeezing past.", "", true),
            new Meta(228, "nonogram", "Nonogram", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Fill a grid from the run lengths written along each row and column.", "", true),
            new Meta(229, "lights-out", "Lights Out", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Turn every light off, where pressing one flips it and its neighbours.", "", true),
            new Meta(230, "peg-solitaire", "Peg Solitaire", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Jump pegs over each other to leave a single peg in the centre.", "", true),
            new Meta(231, "mastermind", "Mastermind", "Logic and Puzzle Games", Kind.GAME, Difficulty.BEGINNER, "Deduce a hidden colour code from black and white peg feedback.", "", true),
            new Meta(232, "kakuro", "Kakuro", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "A crossword with sums: fill runs of digits that add to the given totals.", "", true),
            new Meta(233, "futoshiki", "Futoshiki", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "A Latin square with greater-than signs constraining neighbouring cells.", "", true),
            new Meta(234, "kenken", "Kenken", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "A Latin square where outlined cages must reach a target by one operation.", "", true),
            new Meta(235, "slitherlink", "Slitherlink", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Draw a single closed loop so each number has that many edges around it.", "", true),
            new Meta(236, "hashiwokakero", "Hashiwokakero", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Join islands with bridges so every island has its count and all connect.", "", true),
            new Meta(237, "nurikabe", "Nurikabe", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Divide a grid into numbered islands separated by one connected wall.", "", true),
            new Meta(238, "hitori", "Hitori", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Black out cells so no number repeats in a line and the rest stay joined.", "", true),
            new Meta(239, "binary-puzzle", "Binary Puzzle", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Fill a grid with two symbols, never three in a row, balanced and all rows distinct.", "", true),
            new Meta(240, "skyscrapers", "Skyscrapers", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Place building heights so each edge clue counts the skyline visible from it.", "", true),
            new Meta(241, "shikaku", "Shikaku", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Cut a grid into rectangles, each containing one number equal to its area.", "", true),
            new Meta(242, "magic-square", "Magic Square", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Arrange numbers so every row, column and diagonal adds to the same total.", "", true),
            new Meta(243, "cryptarithm", "Cryptarithm", "Logic and Puzzle Games", Kind.TOOL, Difficulty.INTERMEDIATE, "Solve puzzles like SEND + MORE = MONEY by assigning a digit to each letter.", "", true),
            new Meta(244, "zebra-puzzle", "Zebra Puzzle", "Logic and Puzzle Games", Kind.TOOL, Difficulty.ADVANCED, "Work out who owns the zebra from a list of constraints, by elimination.", "", false),
            new Meta(245, "river-crossing", "River Crossing", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Get everyone across without leaving the wrong pair alone together.", "", false),
            new Meta(246, "water-jug", "Water Jug", "Logic and Puzzle Games", Kind.TOOL, Difficulty.INTERMEDIATE, "Measure an exact amount using jugs that have no markings.", "", true),
            new Meta(247, "rush-hour", "Rush Hour", "Logic and Puzzle Games", Kind.GRID, Difficulty.ADVANCED, "Slide blocking cars aside to drive the red car out of the jam.", "", false),
            new Meta(248, "knights-tour", "Knights Tour", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Move a knight to every square on the board exactly once.", "", true),
            new Meta(249, "word-search-generator", "Word Search Generator", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Hide a word list in a grid of letters, then solve it back.", "", false),
            new Meta(250, "tangram", "Tangram", "Logic and Puzzle Games", Kind.GRID, Difficulty.INTERMEDIATE, "Fit seven flat shapes together to match a silhouette exactly.", "", false),
            new Meta(251, "mate-in-n", "Mate In N", "Logic and Puzzle Games", Kind.GRID, Difficulty.ADVANCED, "Search a chess position for a forced checkmate in a given number of moves.", "", false));

    /** Slug to fully-qualified class name. Strings, so nothing is loaded. */
    private static final String[][] CLASS_NAMES = {
            {"simple-calculator", "com.randomjava.projects.simplecalculator.SimpleCalculator"},
            {"todo-list", "com.randomjava.projects.todolist.TodoList"},
            {"digital-clock", "com.randomjava.projects.digitalclock.DigitalClock"},
            {"bmi-calculator", "com.randomjava.projects.bmicalculator.BmiCalculator"},
            {"currency-converter", "com.randomjava.projects.currencyconverter.CurrencyConverter"},
            {"random-quote-generator", "com.randomjava.projects.randomquotegenerator.RandomQuoteGenerator"},
            {"weather-app", "com.randomjava.projects.weatherapp.WeatherApp"},
            {"unit-converter", "com.randomjava.projects.unitconverter.UnitConverter"},
            {"rock-paper-scissors", "com.randomjava.projects.rockpaperscissors.RockPaperScissors"},
            {"countdown-timer", "com.randomjava.projects.countdowntimer.CountdownTimer"},
            {"personal-budget-tracker", "com.randomjava.projects.personalbudgettracker.PersonalBudgetTracker"},
            {"markdown-to-html", "com.randomjava.projects.markdowntohtml.MarkdownToHtml"},
            {"chat-application", "com.randomjava.projects.chatapplication.ChatApplication"},
            {"file-encryption-tool", "com.randomjava.projects.fileencryptiontool.FileEncryptionTool"},
            {"recipe-finder", "com.randomjava.projects.recipefinder.RecipeFinder"},
            {"image-watermarking-tool", "com.randomjava.projects.imagewatermarkingtool.ImageWatermarkingTool"},
            {"expense-splitting-app", "com.randomjava.projects.expensesplittingapp.ExpenseSplittingApp"},
            {"qr-code-generator", "com.randomjava.projects.qrcodegenerator.QrCodeGenerator"},
            {"blog-cms", "com.randomjava.projects.blogcms.BlogCms"},
            {"habit-tracker", "com.randomjava.projects.habittracker.HabitTracker"},
            {"sudoku-solver", "com.randomjava.projects.sudokusolver.SudokuSolver"},
            {"maze-generator", "com.randomjava.projects.mazegenerator.MazeGenerator"},
            {"pathfinding-visualizer", "com.randomjava.projects.pathfindingvisualizer.PathfindingVisualizer"},
            {"sorting-visualizer", "com.randomjava.projects.sortingvisualizer.SortingVisualizer"},
            {"binary-search-tree-visualizer", "com.randomjava.projects.binarysearchtreevisualizer.BinarySearchTreeVisualizer"},
            {"graph-traversal-simulator", "com.randomjava.projects.graphtraversalsimulator.GraphTraversalSimulator"},
            {"anagram-finder", "com.randomjava.projects.anagramfinder.AnagramFinder"},
            {"palindrome-checker", "com.randomjava.projects.palindromechecker.PalindromeChecker"},
            {"prime-number-generator", "com.randomjava.projects.primenumbergenerator.PrimeNumberGenerator"},
            {"knapsack-solver", "com.randomjava.projects.knapsacksolver.KnapsackSolver"},
            {"portfolio-website", "com.randomjava.projects.portfoliowebsite.PortfolioWebsite"},
            {"e-commerce-store", "com.randomjava.projects.ecommercestore.ECommerceStore"},
            {"url-shortener", "com.randomjava.projects.urlshortener.UrlShortener"},
            {"polling-voting-app", "com.randomjava.projects.pollingvotingapp.PollingVotingApp"},
            {"job-board", "com.randomjava.projects.jobboard.JobBoard"},
            {"social-media-dashboard", "com.randomjava.projects.socialmediadashboard.SocialMediaDashboard"},
            {"event-booking-system", "com.randomjava.projects.eventbookingsystem.EventBookingSystem"},
            {"online-whiteboard", "com.randomjava.projects.onlinewhiteboard.OnlineWhiteboard"},
            {"blog-with-comments", "com.randomjava.projects.blogwithcomments.BlogWithComments"},
            {"newsletter-subscription", "com.randomjava.projects.newslettersubscription.NewsletterSubscription"},
            {"fitness-tracker", "com.randomjava.projects.fitnesstracker.FitnessTracker"},
            {"meditation-timer", "com.randomjava.projects.meditationtimer.MeditationTimer"},
            {"grocery-list-app", "com.randomjava.projects.grocerylistapp.GroceryListApp"},
            {"language-flashcards", "com.randomjava.projects.languageflashcards.LanguageFlashcards"},
            {"expense-tracker", "com.randomjava.projects.expensetracker.ExpenseTracker"},
            {"mood-journal", "com.randomjava.projects.moodjournal.MoodJournal"},
            {"plant-care-reminder", "com.randomjava.projects.plantcarereminder.PlantCareReminder"},
            {"local-event-finder", "com.randomjava.projects.localeventfinder.LocalEventFinder"},
            {"parking-spot-locator", "com.randomjava.projects.parkingspotlocator.ParkingSpotLocator"},
            {"recipe-organizer", "com.randomjava.projects.recipeorganizer.RecipeOrganizer"},
            {"spam-email-classifier", "com.randomjava.projects.spamemailclassifier.SpamEmailClassifier"},
            {"handwritten-digit-recognizer", "com.randomjava.projects.handwrittendigitrecognizer.HandwrittenDigitRecognizer"},
            {"movie-recommendation-system", "com.randomjava.projects.movierecommendationsystem.MovieRecommendationSystem"},
            {"sentiment-analysis-tool", "com.randomjava.projects.sentimentanalysistool.SentimentAnalysisTool"},
            {"faq-chatbot", "com.randomjava.projects.faqchatbot.FaqChatbot"},
            {"image-caption-generator", "com.randomjava.projects.imagecaptiongenerator.ImageCaptionGenerator"},
            {"stock-price-predictor", "com.randomjava.projects.stockpricepredictor.StockPricePredictor"},
            {"voice-command-assistant", "com.randomjava.projects.voicecommandassistant.VoiceCommandAssistant"},
            {"resume-screener", "com.randomjava.projects.resumescreener.ResumeScreener"},
            {"music-genre-classifier", "com.randomjava.projects.musicgenreclassifier.MusicGenreClassifier"},
            {"password-strength-checker", "com.randomjava.projects.passwordstrengthchecker.PasswordStrengthChecker"},
            {"secure-file-transfer", "com.randomjava.projects.securefiletransfer.SecureFileTransfer"},
            {"port-scanner", "com.randomjava.projects.portscanner.PortScanner"},
            {"keylogger-detector", "com.randomjava.projects.keyloggerdetector.KeyloggerDetector"},
            {"two-factor-authentication", "com.randomjava.projects.twofactorauthentication.TwoFactorAuthentication"},
            {"encrypted-chat-app", "com.randomjava.projects.encryptedchatapp.EncryptedChatApp"},
            {"honeypot-server", "com.randomjava.projects.honeypotserver.HoneypotServer"},
            {"brute-force-simulator", "com.randomjava.projects.bruteforcesimulator.BruteForceSimulator"},
            {"secure-note-taking-app", "com.randomjava.projects.securenotetakingapp.SecureNoteTakingApp"},
            {"digital-signature-generator", "com.randomjava.projects.digitalsignaturegenerator.DigitalSignatureGenerator"},
            {"snake", "com.randomjava.projects.snake.Snake"},
            {"tetris", "com.randomjava.projects.tetris.Tetris"},
            {"memory-matching-game", "com.randomjava.projects.memorymatchinggame.MemoryMatchingGame"},
            {"platformer-2d", "com.randomjava.projects.platformer2d.Platformer2d"},
            {"chess-engine", "com.randomjava.projects.chessengine.ChessEngine"},
            {"multiplayer-trivia", "com.randomjava.projects.multiplayertrivia.MultiplayerTrivia"},
            {"space-shooter", "com.randomjava.projects.spaceshooter.SpaceShooter"},
            {"word-scramble", "com.randomjava.projects.wordscramble.WordScramble"},
            {"virtual-pet", "com.randomjava.projects.virtualpet.VirtualPet"},
            {"tower-defense", "com.randomjava.projects.towerdefense.TowerDefense"},
            {"covid-data-dashboard", "com.randomjava.projects.coviddatadashboard.CovidDataDashboard"},
            {"sales-forecasting", "com.randomjava.projects.salesforecasting.SalesForecasting"},
            {"box-office-predictor", "com.randomjava.projects.boxofficepredictor.BoxOfficePredictor"},
            {"customer-churn-analysis", "com.randomjava.projects.customerchurnanalysis.CustomerChurnAnalysis"},
            {"traffic-analysis", "com.randomjava.projects.trafficanalysis.TrafficAnalysis"},
            {"air-quality-monitor", "com.randomjava.projects.airqualitymonitor.AirQualityMonitor"},
            {"crypto-price-tracker", "com.randomjava.projects.cryptopricetracker.CryptoPriceTracker"},
            {"sports-statistics-analyzer", "com.randomjava.projects.sportsstatisticsanalyzer.SportsStatisticsAnalyzer"},
            {"weather-pattern-predictor", "com.randomjava.projects.weatherpatternpredictor.WeatherPatternPredictor"},
            {"energy-consumption-dashboard", "com.randomjava.projects.energyconsumptiondashboard.EnergyConsumptionDashboard"},
            {"file-organizer", "com.randomjava.projects.fileorganizer.FileOrganizer"},
            {"email-automation-bot", "com.randomjava.projects.emailautomationbot.EmailAutomationBot"},
            {"news-web-scraper", "com.randomjava.projects.newswebscraper.NewsWebScraper"},
            {"pdf-merger-splitter", "com.randomjava.projects.pdfmergersplitter.PdfMergerSplitter"},
            {"auto-image-resizer", "com.randomjava.projects.autoimageresizer.AutoImageResizer"},
            {"invoice-generator", "com.randomjava.projects.invoicegenerator.InvoiceGenerator"},
            {"backup-automation", "com.randomjava.projects.backupautomation.BackupAutomation"},
            {"social-post-scheduler", "com.randomjava.projects.socialpostscheduler.SocialPostScheduler"},
            {"data-cleaning-script", "com.randomjava.projects.datacleaningscript.DataCleaningScript"},
            {"auto-form-filler", "com.randomjava.projects.autoformfiller.AutoFormFiller"},
            {"ascii-art-generator", "com.randomjava.projects.asciiartgenerator.AsciiArtGenerator"},
            {"meme-generator", "com.randomjava.projects.memegenerator.MemeGenerator"},
            {"music-visualizer", "com.randomjava.projects.musicvisualizer.MusicVisualizer"},
            {"random-story-generator", "com.randomjava.projects.randomstorygenerator.RandomStoryGenerator"},
            {"pixel-art-editor", "com.randomjava.projects.pixelarteditor.PixelArtEditor"},
            {"virtual-art-gallery", "com.randomjava.projects.virtualartgallery.VirtualArtGallery"},
            {"interactive-map", "com.randomjava.projects.interactivemap.InteractiveMap"},
            {"horoscope-app", "com.randomjava.projects.horoscopeapp.HoroscopeApp"},
            {"poetry-generator", "com.randomjava.projects.poetrygenerator.PoetryGenerator"},
            {"animated-greeting-card", "com.randomjava.projects.animatedgreetingcard.AnimatedGreetingCard"},
            {"volunteer-matching", "com.randomjava.projects.volunteermatching.VolunteerMatching"},
            {"donation-tracker", "com.randomjava.projects.donationtracker.DonationTracker"},
            {"disaster-relief-coordination", "com.randomjava.projects.disasterreliefcoordination.DisasterReliefCoordination"},
            {"blood-donation-finder", "com.randomjava.projects.blooddonationfinder.BloodDonationFinder"},
            {"food-waste-reduction", "com.randomjava.projects.foodwastereduction.FoodWasteReduction"},
            {"accessibility-checker", "com.randomjava.projects.accessibilitychecker.AccessibilityChecker"},
            {"mental-health-support-chatbot", "com.randomjava.projects.mentalhealthsupportchatbot.MentalHealthSupportChatbot"},
            {"public-transport-tracker", "com.randomjava.projects.publictransporttracker.PublicTransportTracker"},
            {"missing-persons-database", "com.randomjava.projects.missingpersonsdatabase.MissingPersonsDatabase"},
            {"community-garden-planner", "com.randomjava.projects.communitygardenplanner.CommunityGardenPlanner"},
            {"blockchain-voting", "com.randomjava.projects.blockchainvoting.BlockchainVoting"},
            {"decentralized-file-storage", "com.randomjava.projects.decentralizedfilestorage.DecentralizedFileStorage"},
            {"iot-home-automation", "com.randomjava.projects.iothomeautomation.IotHomeAutomation"},
            {"drone-control-interface", "com.randomjava.projects.dronecontrolinterface.DroneControlInterface"},
            {"ar-navigation", "com.randomjava.projects.arnavigation.ArNavigation"},
            {"vr-museum-tour", "com.randomjava.projects.vrmuseumtour.VrMuseumTour"},
            {"ai-code-reviewer", "com.randomjava.projects.aicodereviewer.AiCodeReviewer"},
            {"smart-traffic-light", "com.randomjava.projects.smarttrafficlight.SmartTrafficLight"},
            {"number-guessing-game", "com.randomjava.projects.numberguessinggame.NumberGuessingGame"},
            {"tic-tac-toe", "com.randomjava.projects.tictactoe.TicTacToe"},
            {"word-counter", "com.randomjava.projects.wordcounter.WordCounter"},
            {"text-based-adventure", "com.randomjava.projects.textbasedadventure.TextBasedAdventure"},
            {"simple-banking-app", "com.randomjava.projects.simplebankingapp.SimpleBankingApp"},
            {"scientific-calculator", "com.randomjava.projects.scientificcalculator.ScientificCalculator"},
            {"text-editor", "com.randomjava.projects.texteditor.TextEditor"},
            {"brick-breaker", "com.randomjava.projects.brickbreaker.BrickBreaker"},
            {"flappy-bird", "com.randomjava.projects.flappybird.FlappyBird"},
            {"color-hunt-game", "com.randomjava.projects.colorhuntgame.ColorHuntGame"},
            {"digital-steganography", "com.randomjava.projects.digitalsteganography.DigitalSteganography"},
            {"attendance-management", "com.randomjava.projects.attendancemanagement.AttendanceManagement"},
            {"library-management", "com.randomjava.projects.librarymanagement.LibraryManagement"},
            {"grading-system", "com.randomjava.projects.gradingsystem.GradingSystem"},
            {"school-management", "com.randomjava.projects.schoolmanagement.SchoolManagement"},
            {"cgpa-calculator", "com.randomjava.projects.cgpacalculator.CgpaCalculator"},
            {"exam-seating-arrangement", "com.randomjava.projects.examseatingarrangement.ExamSeatingArrangement"},
            {"atm-simulation", "com.randomjava.projects.atmsimulation.AtmSimulation"},
            {"pharmacy-management", "com.randomjava.projects.pharmacymanagement.PharmacyManagement"},
            {"supermarket-billing", "com.randomjava.projects.supermarketbilling.SupermarketBilling"},
            {"supply-chain-management", "com.randomjava.projects.supplychainmanagement.SupplyChainManagement"},
            {"helpdesk-management", "com.randomjava.projects.helpdeskmanagement.HelpdeskManagement"},
            {"online-quiz-management", "com.randomjava.projects.onlinequizmanagement.OnlineQuizManagement"},
            {"crime-records-management", "com.randomjava.projects.crimerecordsmanagement.CrimeRecordsManagement"},
            {"criminal-face-detection", "com.randomjava.projects.criminalfacedetection.CriminalFaceDetection"},
            {"bug-tracking-system", "com.randomjava.projects.bugtrackingsystem.BugTrackingSystem"},
            {"customer-relationship-manager", "com.randomjava.projects.customerrelationshipmanager.CustomerRelationshipManager"},
            {"id-card-generator", "com.randomjava.projects.idcardgenerator.IdCardGenerator"},
            {"cv-resume-builder", "com.randomjava.projects.cvresumebuilder.CvResumeBuilder"},
            {"airline-reservation", "com.randomjava.projects.airlinereservation.AirlineReservation"},
            {"smart-city-guide", "com.randomjava.projects.smartcityguide.SmartCityGuide"},
            {"online-cab-booking", "com.randomjava.projects.onlinecabbooking.OnlineCabBooking"},
            {"simple-search-engine", "com.randomjava.projects.simplesearchengine.SimpleSearchEngine"},
            {"social-networking-site", "com.randomjava.projects.socialnetworkingsite.SocialNetworkingSite"},
            {"email-system", "com.randomjava.projects.emailsystem.EmailSystem"},
            {"office-vpn", "com.randomjava.projects.officevpn.OfficeVpn"},
            {"rubiks-cube-3x3", "com.randomjava.projects.rubikscube3x3.RubiksCube3x3"},
            {"pocket-cube-2x2", "com.randomjava.projects.pocketcube2x2.PocketCube2x2"},
            {"revenge-cube-4x4", "com.randomjava.projects.revengecube4x4.RevengeCube4x4"},
            {"professor-cube-5x5", "com.randomjava.projects.professorcube5x5.ProfessorCube5x5"},
            {"v-cube-6x6", "com.randomjava.projects.vcube6x6.VCube6x6"},
            {"v-cube-7x7", "com.randomjava.projects.vcube7x7.VCube7x7"},
            {"void-cube", "com.randomjava.projects.voidcube.VoidCube"},
            {"mirror-cube", "com.randomjava.projects.mirrorcube.MirrorCube"},
            {"axis-cube", "com.randomjava.projects.axiscube.AxisCube"},
            {"pyraminx", "com.randomjava.projects.pyraminx.Pyraminx"},
            {"skewb", "com.randomjava.projects.skewb.Skewb"},
            {"megaminx", "com.randomjava.projects.megaminx.Megaminx"},
            {"square-1", "com.randomjava.projects.square1.Square1"},
            {"rubiks-clock", "com.randomjava.projects.rubiksclock.RubiksClock"},
            {"pyramorphix", "com.randomjava.projects.pyramorphix.Pyramorphix"},
            {"gear-cube", "com.randomjava.projects.gearcube.GearCube"},
            {"dino-cube", "com.randomjava.projects.dinocube.DinoCube"},
            {"floppy-cube", "com.randomjava.projects.floppycube.FloppyCube"},
            {"cfop-trainer", "com.randomjava.projects.cfoptrainer.CfopTrainer"},
            {"method-comparison", "com.randomjava.projects.methodcomparison.MethodComparison"},
            {"speedcube-timer", "com.randomjava.projects.speedcubetimer.SpeedcubeTimer"},
            {"cube-1x1x1", "com.randomjava.projects.cube1x1x1.Cube1x1x1"},
            {"cube-8x8x8", "com.randomjava.projects.cube8x8x8.Cube8x8x8"},
            {"cube-9x9x9", "com.randomjava.projects.cube9x9x9.Cube9x9x9"},
            {"cube-10x10x10", "com.randomjava.projects.cube10x10x10.Cube10x10x10"},
            {"cube-11x11x11", "com.randomjava.projects.cube11x11x11.Cube11x11x11"},
            {"cube-12x12x12", "com.randomjava.projects.cube12x12x12.Cube12x12x12"},
            {"cube-13x13x13", "com.randomjava.projects.cube13x13x13.Cube13x13x13"},
            {"cube-14x14x14", "com.randomjava.projects.cube14x14x14.Cube14x14x14"},
            {"cube-15x15x15", "com.randomjava.projects.cube15x15x15.Cube15x15x15"},
            {"cube-16x16x16", "com.randomjava.projects.cube16x16x16.Cube16x16x16"},
            {"cube-17x17x17", "com.randomjava.projects.cube17x17x17.Cube17x17x17"},
            {"cube-19x19x19", "com.randomjava.projects.cube19x19x19.Cube19x19x19"},
            {"cube-21x21x21", "com.randomjava.projects.cube21x21x21.Cube21x21x21"},
            {"cube-22x22x22", "com.randomjava.projects.cube22x22x22.Cube22x22x22"},
            {"cube-23x23x23", "com.randomjava.projects.cube23x23x23.Cube23x23x23"},
            {"cube-25x25x25", "com.randomjava.projects.cube25x25x25.Cube25x25x25"},
            {"cube-28x28x28", "com.randomjava.projects.cube28x28x28.Cube28x28x28"},
            {"cube-29x29x29", "com.randomjava.projects.cube29x29x29.Cube29x29x29"},
            {"cube-33x33x33", "com.randomjava.projects.cube33x33x33.Cube33x33x33"},
            {"cube-34x34x34", "com.randomjava.projects.cube34x34x34.Cube34x34x34"},
            {"cube-35x35x35", "com.randomjava.projects.cube35x35x35.Cube35x35x35"},
            {"cube-49x49x49", "com.randomjava.projects.cube49x49x49.Cube49x49x49"},
            {"cube-100x100x100", "com.randomjava.projects.cube100x100x100.Cube100x100x100"},
            {"fisher-cube", "com.randomjava.projects.fishercube.FisherCube"},
            {"windmill-cube", "com.randomjava.projects.windmillcube.WindmillCube"},
            {"ghost-cube", "com.randomjava.projects.ghostcube.GhostCube"},
            {"mastermorphix", "com.randomjava.projects.mastermorphix.Mastermorphix"},
            {"bandaged-cube", "com.randomjava.projects.bandagedcube.BandagedCube"},
            {"dreidel-cube", "com.randomjava.projects.dreidelcube.DreidelCube"},
            {"x-cube", "com.randomjava.projects.xcube.XCube"},
            {"bump-cube", "com.randomjava.projects.bumpcube.BumpCube"},
            {"camouflage-cube", "com.randomjava.projects.camouflagecube.CamouflageCube"},
            {"truncated-cube", "com.randomjava.projects.truncatedcube.TruncatedCube"},
            {"cylindrical-cube", "com.randomjava.projects.cylindricalcube.CylindricalCube"},
            {"windmill-morphix", "com.randomjava.projects.windmillmorphix.WindmillMorphix"},
            {"junior-cube", "com.randomjava.projects.juniorcube.JuniorCube"},
            {"tower-of-hanoi", "com.randomjava.projects.towerofhanoi.TowerOfHanoi"},
            {"n-queens", "com.randomjava.projects.nqueens.NQueens"},
            {"sliding-15-puzzle", "com.randomjava.projects.sliding15puzzle.Sliding15Puzzle"},
            {"minesweeper", "com.randomjava.projects.minesweeper.Minesweeper"},
            {"game-2048", "com.randomjava.projects.game2048.Game2048"},
            {"sokoban", "com.randomjava.projects.sokoban.Sokoban"},
            {"nonogram", "com.randomjava.projects.nonogram.Nonogram"},
            {"lights-out", "com.randomjava.projects.lightsout.LightsOut"},
            {"peg-solitaire", "com.randomjava.projects.pegsolitaire.PegSolitaire"},
            {"mastermind", "com.randomjava.projects.mastermind.Mastermind"},
            {"kakuro", "com.randomjava.projects.kakuro.Kakuro"},
            {"futoshiki", "com.randomjava.projects.futoshiki.Futoshiki"},
            {"kenken", "com.randomjava.projects.kenken.Kenken"},
            {"slitherlink", "com.randomjava.projects.slitherlink.Slitherlink"},
            {"hashiwokakero", "com.randomjava.projects.hashiwokakero.Hashiwokakero"},
            {"nurikabe", "com.randomjava.projects.nurikabe.Nurikabe"},
            {"hitori", "com.randomjava.projects.hitori.Hitori"},
            {"binary-puzzle", "com.randomjava.projects.binarypuzzle.BinaryPuzzle"},
            {"skyscrapers", "com.randomjava.projects.skyscrapers.Skyscrapers"},
            {"shikaku", "com.randomjava.projects.shikaku.Shikaku"},
            {"magic-square", "com.randomjava.projects.magicsquare.MagicSquare"},
            {"cryptarithm", "com.randomjava.projects.cryptarithm.Cryptarithm"},
            {"zebra-puzzle", "com.randomjava.projects.zebrapuzzle.ZebraPuzzle"},
            {"river-crossing", "com.randomjava.projects.rivercrossing.RiverCrossing"},
            {"water-jug", "com.randomjava.projects.waterjug.WaterJug"},
            {"rush-hour", "com.randomjava.projects.rushhour.RushHour"},
            {"knights-tour", "com.randomjava.projects.knightstour.KnightsTour"},
            {"word-search-generator", "com.randomjava.projects.wordsearchgenerator.WordSearchGenerator"},
            {"tangram", "com.randomjava.projects.tangram.Tangram"},
            {"mate-in-n", "com.randomjava.projects.mateinn.MateInN"}
    };

    private static final Map<String, Supplier<Project>> FACTORIES = buildFactories();

    private static Map<String, Supplier<Project>> buildFactories() {
        Map<String, Supplier<Project>> map = new LinkedHashMap<>();
        for (String[] row : CLASS_NAMES) {
            // One lambda body for all 251 entries, closing over a
            // string. Writing Foo::new here instead would be 251
            // separate call sites, each needing its class loaded to link.
            String className = row[1];
            map.put(row[0], () -> instantiate(className));
        }
        return Collections.unmodifiableMap(map);
    }

    private static Project instantiate(String className) {
        try {
            return (Project) Class.forName(className)
                    .getDeclaredConstructor()
                    .newInstance();
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException(
                    "Cannot create " + className + ". The catalogue and the project classes "
                    + "have got out of step; regenerate with tools/generate.py.", e);
        }
    }

    /** Every project, in catalogue order. */
    public static List<Meta> all() {
        return ALL;
    }

    /** Slug to a factory that loads and constructs the project on demand. */
    public static Map<String, Supplier<Project>> factories() {
        return FACTORIES;
    }
}
