package com.randomjava.projects.cfoptrainer;

import com.randomjava.cube.FaceletCube;
import com.randomjava.cube.Move;
import com.randomjava.lib.ConsoleUI;
import com.randomjava.lib.Difficulty;
import com.randomjava.lib.Json;
import com.randomjava.lib.Kind;
import com.randomjava.lib.Meta;
import com.randomjava.lib.Project;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Random;

/**
 * Drills the last-layer algorithms: recognise the case, recall the algorithm.
 *
 * <p>Cases are not stored as pictures. Each one is generated by applying its
 * algorithm backwards to a solved cube, which is exactly the position that
 * algorithm undoes. That means a case can never disagree with its answer: if an
 * algorithm here were wrong, the case it produces would simply not be solved by
 * it, and the self check below would say so.
 */
public final class CfopTrainer implements Project {

    public static final Meta META = new Meta(183, "cfop-trainer", "CFOP Trainer", "Cube Solving Methods", Kind.LIST,
            Difficulty.ADVANCED, "Drill the last-layer cases: recognise the pattern, recall the algorithm.",
            "", true);

    /** A named last-layer case. */
    public record Case(String group, String name, String algorithm) {
    }

    private static final List<Case> CASES = List.of(
            // Permutation of the last layer: all 21 cases.
            new Case("PLL", "Aa", "x L2 D2 L' U' L D2 L' U L' x'"),
            new Case("PLL", "Ab", "x' L2 D2 L U L' D2 L U' L x"),
            new Case("PLL", "E", "x' L' U L D' L' U' L D L' U' L D' L' U L D x"),
            new Case("PLL", "F", "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R"),
            new Case("PLL", "Ga", "R2 U R' U R' U' R U' R2 U' D R' U R D'"),
            new Case("PLL", "Gb", "R' U' R U D' R2 U R' U R U' R U' R2 D"),
            new Case("PLL", "Gc", "R2 U' R U' R U R' U R2 U D' R U' R' D"),
            new Case("PLL", "Gd", "R U R' U' D R2 U' R U' R' U R' U R2 D'"),
            new Case("PLL", "H", "M2 U M2 U2 M2 U M2"),
            new Case("PLL", "Ja", "x R2 F R F' R U2 r' U r U2 x'"),
            new Case("PLL", "Jb", "R U R' F' R U R' U' R' F R2 U' R' U'"),
            new Case("PLL", "Na", "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'"),
            new Case("PLL", "Nb", "R' U R U' R' F' U' F R U R' F R' F' R U' R"),
            new Case("PLL", "Ra", "R U' R' U' R U R D R' U' R D' R' U2 R'"),
            new Case("PLL", "Rb", "R2 F R U R U' R' F' R U2 R' U2 R"),
            new Case("PLL", "T", "R U R' U' R' F R2 U' R' U' R U R' F'"),
            new Case("PLL", "Ua", "R U' R U R U R U' R' U' R2"),
            new Case("PLL", "Ub", "R2 U R U R' U' R' U' R' U R'"),
            new Case("PLL", "V", "R' U R' U' R' U' R' U R U R2"),
            new Case("PLL", "Y", "F R U' R' U' R U R' F' R U R' U' R' F R F'"),
            new Case("PLL", "Z", "M2 U M2 U M' U2 M2 U2 M' U2"),
            // A working two-look OLL set.
            new Case("OLL", "Dot", "F R U R' U' F' f R U R' U' f'"),
            new Case("OLL", "Line", "F R U R' U' F'"),
            new Case("OLL", "L shape", "f R U R' U' f'"),
            new Case("OLL", "Sune", "R U R' U R U2 R'"),
            new Case("OLL", "Antisune", "R U2 R' U' R U' R'"),
            new Case("OLL", "H / double Sune", "R U R' U R U' R' U R U2 R'"),
            new Case("OLL", "Pi", "R U2 R2 U' R2 U' R2 U2 R"),
            new Case("OLL", "T / headlights", "R2 D R' U2 R D' R' U2 R'"),
            new Case("OLL", "L / bowtie", "F' r U R' U' r' F R"));

    private final Random random = new Random();
    private int asked;
    private int correct;
    private Case current;

    @Override
    public Meta meta() {
        return META;
    }

    // ------------------------------------------------------------------
    // Core
    // ------------------------------------------------------------------

    public List<Case> cases() {
        return CASES;
    }

    public List<Case> group(String group) {
        List<Case> out = new ArrayList<>();
        for (Case one : CASES) {
            if (group == null || group.isBlank() || group.equalsIgnoreCase(one.group())) {
                out.add(one);
            }
        }
        return out;
    }

    /** Picks a case to drill and returns the cube showing it. */
    public Case draw(String group) {
        List<Case> pool = group(group);
        current = pool.get(random.nextInt(pool.size()));
        asked++;
        return current;
    }

    public Case current() {
        return current;
    }

    /**
     * The position a case presents: a solved cube with the algorithm applied
     * backwards, which is precisely the state the algorithm undoes.
     */
    public FaceletCube position(Case one) {
        FaceletCube cube = new FaceletCube(3);
        cube.apply(Move.invert(Move.parse(one.algorithm(), 3)));
        return cube;
    }

    /** True when the answer really solves the case, whatever was typed. */
    public boolean check(Case one, String answer) {
        if (answer == null || answer.isBlank()) {
            return false;
        }
        try {
            FaceletCube cube = position(one);
            cube.apply(Move.parse(answer, 3));
            for (int turns = 0; turns < 4; turns++) {
                if (cube.isSolved()) {
                    return true;
                }
                cube.apply(new Move('U', 1, 0, 1));
            }
            return false;
        } catch (RuntimeException e) {
            return false;
        }
    }

    /**
     * Verifies every stored algorithm against the case it generates. A typo in
     * the table shows up here rather than while someone is trying to learn.
     */
    public List<String> selfCheck() {
        List<String> broken = new ArrayList<>();
        for (Case one : CASES) {
            if (!check(one, one.algorithm())) {
                broken.add(one.group() + " " + one.name());
            }
        }
        return broken;
    }

    private String score() {
        return asked == 0 ? "No cases drilled yet."
                : correct + " of " + asked + " right.";
    }

    // ------------------------------------------------------------------
    // Front ends
    // ------------------------------------------------------------------

    @Override
    public void runText(ConsoleUI io) {
        List<String> broken = selfCheck();
        if (broken.isEmpty()) {
            io.muted("All " + CASES.size() + " algorithms verified against their own case.");
        } else {
            io.error("These algorithms do not solve their case: " + String.join(", ", broken));
        }

        while (true) {
            int choice = io.menu("CFOP trainer", List.of(
                    "Drill a PLL case", "Drill an OLL case", "Drill anything", "List every case"));
            if (choice < 0) {
                return;
            }
            if (choice == 3) {
                List<List<String>> rows = new ArrayList<>();
                for (Case one : CASES) {
                    rows.add(List.of(one.group(), one.name(), one.algorithm()));
                }
                io.table(List.of("group", "case", "algorithm"), rows);
                continue;
            }
            String group = choice == 0 ? "PLL" : choice == 1 ? "OLL" : "";
            Case one = draw(group);
            io.println();
            for (String row : position(one).net()) {
                io.println("  " + row);
            }
            io.info("Which case is this, and what solves it?");
            String answer = io.ask("algorithm (or Enter to give up):");
            if (answer.isBlank()) {
                io.result(one.group() + " " + one.name(), one.algorithm());
                continue;
            }
            if (check(one, answer)) {
                correct++;
                io.ok("Right, that solves it. This is " + one.group() + " " + one.name() + ".");
            } else {
                io.error("That does not solve the case.");
                io.result(one.group() + " " + one.name(), one.algorithm());
            }
            io.muted(score());
        }
    }

    @Override
    public Object api(String action, Map<String, Object> body) {
        try {
            switch (action) {
                case "list" -> {
                    List<Map<String, Object>> items = new ArrayList<>();
                    for (Case one : group(Json.str(body, "group", ""))) {
                        items.add(Json.map("id", one.name(), "label",
                                one.group() + "  " + one.name(), "meta", one.algorithm()));
                    }
                    List<String> broken = selfCheck();
                    return Json.ok("items", items,
                            "detail", CASES.size() + " cases stored. "
                                    + (broken.isEmpty()
                                            ? "Every algorithm verified against its own case."
                                            : "Broken: " + String.join(", ", broken)));
                }
                case "draw" -> {
                    Case one = draw(Json.str(body, "group", ""));
                    return Json.ok("board", Json.grid(faceGrid(position(one))),
                            "group", one.group(),
                            "result", "Which " + one.group() + " case is this?",
                            "detail", score());
                }
                case "answer" -> {
                    if (current == null) {
                        return Json.error("Draw a case first.");
                    }
                    boolean right = check(current, Json.str(body, "answer", ""));
                    if (right) {
                        correct++;
                    }
                    return Json.ok("result", right ? "Correct" : "Not quite",
                            "detail", (right ? "That solves the case. " : "That does not solve it. ")
                                    + "This is " + current.group() + " " + current.name()
                                    + ":  " + current.algorithm() + "\n" + score());
                }
                case "reveal" -> {
                    if (current == null) {
                        return Json.error("Draw a case first.");
                    }
                    return Json.ok("result", current.group() + " " + current.name(),
                            "detail", current.algorithm());
                }
                default -> {
                    return Json.error("Unknown action: " + action);
                }
            }
        } catch (RuntimeException e) {
            return Json.error(e.getMessage());
        }
    }

    /** The top face plus the row below it on each side, which is all a case shows. */
    private static char[][] faceGrid(FaceletCube cube) {
        char[][] grid = new char[5][5];
        for (char[] row : grid) {
            java.util.Arrays.fill(row, ' ');
        }
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                grid[i + 1][j + 1] = cube.get(FaceletCube.U, i, j);
            }
            grid[0][i + 1] = cube.get(FaceletCube.B, 0, 2 - i);
            grid[4][i + 1] = cube.get(FaceletCube.F, 0, i);
            grid[i + 1][0] = cube.get(FaceletCube.L, 0, i);
            grid[i + 1][4] = cube.get(FaceletCube.R, 0, 2 - i);
        }
        return grid;
    }
}
