"""The 128-project catalogue.

This is the single source of truth. `generate.py` reads it and emits every
project folder plus `lib/com/randomjava/Catalog.java`.

Each row is:
    (id, slug, kind, done, description)

`kind` picks the scaffold shape:
    TOOL  inputs in, a computed answer out
    LIST  a managed collection of records
    GAME  round or turn based play with a score
    GRID  a 2D board that is rendered and stepped

`done` is True once the project has real hand-written logic. Generated stubs
are never written over a project marked done, so flipping this flag to True is
how you graduate a project out of the scaffold.
"""

CATEGORIES = [
    (1, 10, "Beginner Friendly"),
    (11, 20, "Intermediate"),
    (21, 30, "Algorithms and Data Structures"),
    (31, 40, "Web Development"),
    (41, 50, "Mobile App Ideas"),
    (51, 60, "AI and Machine Learning"),
    (61, 70, "Cybersecurity"),
    (71, 80, "Game Development"),
    (81, 90, "Data Science"),
    (91, 100, "Automation and Tools"),
    (101, 110, "Creative and Fun"),
    (111, 120, "Community and Social Good"),
    (121, 128, "Advanced and Experimental"),
    (129, 139, "Core Java and Games"),
    (140, 145, "School and Campus Systems"),
    (146, 157, "Business and Records Systems"),
    (158, 164, "Travel, City and Communication"),
    (165, 182, "Twisty Puzzles"),
    (183, 185, "Cube Solving Methods"),
    (186, 208, "Big Cubes"),
    (209, 221, "Shape Modifications"),
    (222, 251, "Logic and Puzzle Games"),
]

# Difficulty when a project does not name its own. Categories are broadly
# consistent in ambition, so a default plus a short override list beats
# repeating the value on all 164 rows.
CATEGORY_DIFFICULTY = {
    "Beginner Friendly": "beginner",
    "Intermediate": "intermediate",
    "Algorithms and Data Structures": "intermediate",
    "Web Development": "intermediate",
    "Mobile App Ideas": "beginner",
    "AI and Machine Learning": "advanced",
    "Cybersecurity": "advanced",
    "Game Development": "intermediate",
    "Data Science": "intermediate",
    "Automation and Tools": "beginner",
    "Creative and Fun": "beginner",
    "Community and Social Good": "intermediate",
    "Advanced and Experimental": "advanced",
    "Core Java and Games": "beginner",
    "School and Campus Systems": "beginner",
    "Business and Records Systems": "beginner",
    "Travel, City and Communication": "intermediate",
    "Twisty Puzzles": "advanced",
    "Cube Solving Methods": "advanced",
    "Big Cubes": "advanced",
    "Shape Modifications": "advanced",
    "Logic and Puzzle Games": "intermediate",
}

# Projects that are harder or easier than their category suggests.
DIFFICULTY_OVERRIDES = {
    27: "beginner", 28: "beginner", 29: "beginner",      # anagrams, palindromes, primes
    21: "advanced", 23: "advanced", 25: "advanced",      # sudoku, pathfinding, BST
    61: "beginner", 68: "beginner",                      # password scoring, crack-time maths
    65: "intermediate",
    75: "advanced", 80: "advanced", 74: "advanced",      # chess, tower defence, platformer
    73: "beginner", 78: "beginner", 79: "beginner",                      # word scramble, virtual pet
    101: "beginner", 102: "beginner", 108: "beginner",
    103: "intermediate", 105: "intermediate", 107: "intermediate",
    116: "beginner",
    # New arrivals that differ from their category default.
    134: "intermediate", 135: "advanced",
    137: "intermediate", 138: "intermediate", 139: "advanced",
    144: "intermediate", 145: "intermediate",
    152: "intermediate", 153: "advanced", 154: "advanced",
    155: "advanced", 156: "intermediate", 157: "intermediate",
    158: "beginner", 159: "beginner",
    162: "advanced", 163: "advanced",
    # Twisty puzzles, by how much there is to learn rather than how big they are.
    166: "intermediate", 186: "beginner", 174: "intermediate", 175: "intermediate",
    178: "intermediate", 179: "intermediate", 180: "intermediate",
    181: "beginner", 182: "beginner", 185: "beginner",
    222: "beginner", 224: "beginner", 226: "beginner", 231: "beginner",
    244: "advanced", 247: "advanced", 251: "advanced",
}

# The stack the original brief recommended. The suite itself is always plain
# JDK with no dependencies; this is a note about how you would build the thing
# for real, recorded so the intent is not lost. Blank means the brief for that
# project never named one.
STACKS = {
    129: "Core Java, JavaFX",
    130: "Core Java, JavaFX, 2D arrays",
    131: "Core Java, JavaFX, string manipulation",
    132: "Core Java, Java Collections, file I/O",
    133: "Core Java, JavaFX, file handling, Collections",
    134: "Core Java, JavaFX, Java math libraries",
    135: "Core Java, JavaFX, file I/O",
    136: "Core Java, JavaFX, 2D graphics and event handling",
    137: "Core Java, JavaFX, animation and collision detection",
    138: "Core Java, JavaFX, timers and event handling",
    139: "Core Java, JavaFX, Java Image I/O, encryption libraries, MySQL",
    140: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    141: "Spring Boot, MySQL, Hibernate, Thymeleaf, Spring Security",
    142: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    143: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    144: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    145: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    146: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    147: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    148: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    149: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    150: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    151: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    152: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    153: "Core Java, OpenCV, DeepLearning4J, MySQL, JavaFX",
    154: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    155: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    156: "Spring Boot, MySQL, Thymeleaf, iText, Spring Security",
    157: "Spring Boot, MySQL, Thymeleaf, iText, Spring Security",
    158: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    159: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    160: "Spring Boot, MySQL, Thymeleaf, Spring Security, Hibernate",
    161: "Spring Boot, MySQL, Apache Lucene, Thymeleaf, Spring Security",
    162: "Spring Boot, MySQL, Thymeleaf, Spring Security, WebSocket",
    163: "Spring Boot, JavaMail API, MySQL, Thymeleaf, Spring Security",
    164: "Core Java, Java sockets, MySQL, JavaFX, Java security libraries",
}

PROJECTS = [
    # -- Beginner Friendly ------------------------------------------------
    (1, "simple-calculator", "TOOL", True,
     "Evaluate an arithmetic expression with +, -, *, /, %, ^ and parentheses."),
    (2, "todo-list", "LIST", True,
     "Keep a list of tasks you can add to, tick off and clear."),
    (3, "digital-clock", "TOOL", True,
     "Show the current time, with timezone and 12 or 24 hour formatting."),
    (4, "bmi-calculator", "TOOL", True,
     "Work out body mass index from height and weight, in metric or imperial."),
    (5, "currency-converter", "TOOL", True,
     "Convert an amount between currencies using a rate table."),
    (6, "random-quote-generator", "TOOL", True,
     "Pull a random quote, optionally filtered by topic or author."),
    (7, "weather-app", "TOOL", False,
     "Look up current conditions for a city from a weather API."),
    (8, "unit-converter", "TOOL", True,
     "Convert length, mass, temperature, volume, speed and data sizes."),
    (9, "rock-paper-scissors", "GAME", True,
     "Play best-of against the computer and keep a running score."),
    (10, "countdown-timer", "TOOL", True,
     "Count down from a duration and report the time remaining."),

    # -- Intermediate -----------------------------------------------------
    (11, "personal-budget-tracker", "LIST", False,
     "Record income and spending by category and see what is left."),
    (12, "markdown-to-html", "TOOL", True,
     "Convert Markdown text into HTML: headings, emphasis, lists, code, links."),
    (13, "chat-application", "LIST", False,
     "Socket-backed chat with groups, friends, stored history and voice or video calls."),
    (14, "file-encryption-tool", "TOOL", False,
     "Encrypt and decrypt text or files with a passphrase-derived key."),
    (15, "recipe-finder", "LIST", False,
     "Search recipes by ingredient and save the ones you like."),
    (16, "image-watermarking-tool", "TOOL", False,
     "Stamp text or an image watermark onto a picture."),
    (17, "expense-splitting-app", "LIST", False,
     "Split shared costs across a group and settle up with fewest transfers."),
    (18, "qr-code-generator", "GRID", False,
     "Encode text as a QR matrix and render it as a grid."),
    (19, "blog-cms", "LIST", False,
     "Create, edit, publish and delete blog posts."),
    (20, "habit-tracker", "LIST", False,
     "Track daily habits and keep streaks alive."),

    # -- Algorithms and Data Structures ------------------------------------
    (21, "sudoku-solver", "GRID", True,
     "Solve a 9x9 Sudoku with constraint-checked backtracking."),
    (22, "maze-generator", "GRID", True,
     "Carve a perfect maze with randomised depth-first search, then solve it."),
    (23, "pathfinding-visualizer", "GRID", False,
     "Watch A* and Dijkstra explore a weighted grid toward a goal."),
    (24, "sorting-visualizer", "GRID", True,
     "Step through bubble, insertion, selection, merge and quick sort."),
    (25, "binary-search-tree-visualizer", "GRID", False,
     "Insert, delete and search in a BST and draw the shape it takes."),
    (26, "graph-traversal-simulator", "GRID", False,
     "Run breadth-first and depth-first search over a graph, step by step."),
    (27, "anagram-finder", "TOOL", True,
     "Group words that are anagrams and test whether two strings match."),
    (28, "palindrome-checker", "TOOL", True,
     "Test words, phrases and numbers for palindromes, ignoring punctuation."),
    (29, "prime-number-generator", "TOOL", True,
     "Sieve primes up to a limit, factorise a number and test primality."),
    (30, "knapsack-solver", "TOOL", True,
     "Maximise value under a weight limit with dynamic programming."),

    # -- Web Development ---------------------------------------------------
    (31, "portfolio-website", "LIST", False,
     "Manage the projects, skills and links that make up a portfolio page."),
    (32, "e-commerce-store", "LIST", False,
     "Browse and buy from a catalogue, with a cart, checkout totals, returns and stock."),
    (33, "url-shortener", "LIST", True,
     "Mint short codes for long URLs and count the redirects."),
    (34, "polling-voting-app", "LIST", False,
     "Run an election: anonymous one-per-person voting, secure tallies and published results."),
    (35, "job-board", "LIST", False,
     "Recruiters post openings, candidates apply and search, and applications get screened."),
    (36, "social-media-dashboard", "LIST", False,
     "Pull post metrics into one place and rank by engagement."),
    (37, "event-booking-system", "LIST", False,
     "Hold events with limited seats and take bookings against them."),
    (38, "online-whiteboard", "GRID", False,
     "A shared drawing surface you can paint, erase and clear."),
    (39, "blog-with-comments", "LIST", False,
     "Posts plus threaded comments with moderation."),
    (40, "newsletter-subscription", "LIST", False,
     "Collect subscribers, confirm them and handle unsubscribes."),

    # -- Mobile App Ideas ---------------------------------------------------
    (41, "fitness-tracker", "LIST", False,
     "Log workouts, sets and distance, and total the week."),
    (42, "meditation-timer", "TOOL", False,
     "Timed sessions with interval bells and a warm-up."),
    (43, "grocery-list-app", "LIST", False,
     "Shopping list grouped by aisle with quantities."),
    (44, "language-flashcards", "GAME", False,
     "Spaced-repetition flashcards that resurface what you get wrong."),
    (45, "expense-tracker", "LIST", True,
     "Log spending, tag it, and summarise by category and month."),
    (46, "mood-journal", "LIST", False,
     "Record a daily mood with a note and look for patterns."),
    (47, "plant-care-reminder", "LIST", False,
     "Track watering schedules and flag plants that are overdue."),
    (48, "local-event-finder", "LIST", False,
     "Browse nearby events by date, distance and category."),
    (49, "parking-spot-locator", "GRID", False,
     "Map a car park and find the closest free bay."),
    (50, "recipe-organizer", "LIST", False,
     "Store recipes with tags, servings and a scaled ingredient list."),

    # -- AI and Machine Learning --------------------------------------------
    (51, "spam-email-classifier", "TOOL", True,
     "Score a message as spam or not with a naive Bayes model."),
    (52, "handwritten-digit-recognizer", "GRID", True,
     "Draw a digit on a grid and classify it against trained templates."),
    (53, "movie-recommendation-system", "TOOL", True,
     "Recommend titles from ratings with collaborative filtering."),
    (54, "sentiment-analysis-tool", "TOOL", True,
     "Rate text as positive, negative or neutral with a scored lexicon."),
    (55, "faq-chatbot", "LIST", True,
     "Answer questions by matching them to the closest known FAQ entry."),
    (56, "image-caption-generator", "TOOL", True,
     "Describe an image from detected features and templates."),
    (57, "stock-price-predictor", "TOOL", True,
     "Project a price from history with moving averages and regression."),
    (58, "voice-command-assistant", "LIST", True,
     "Parse spoken or typed commands and dispatch them to handlers."),
    (59, "resume-screener", "TOOL", True,
     "Score a CV against a job description by keyword and experience."),
    (60, "music-genre-classifier", "TOOL", False,
     "Predict a genre from tempo, energy and spectral features."),

    # -- Cybersecurity ------------------------------------------------------
    (61, "password-strength-checker", "TOOL", True,
     "Score a password on length, variety and entropy, and explain the score."),
    (62, "secure-file-transfer", "TOOL", True,
     "Move a file between hosts with encryption and an integrity check."),
    (63, "port-scanner", "LIST", True,
     "Probe this machine for open TCP ports and name the usual services."),
    (64, "keylogger-detector", "LIST", True,
     "Flag processes and hooks that look like they are capturing keystrokes."),
    (65, "two-factor-authentication", "TOOL", True,
     "Generate and verify time-based one-time passwords."),
    (66, "encrypted-chat-app", "LIST", True,
     "Chat where every message is encrypted before it leaves the client."),
    (67, "honeypot-server", "LIST", True,
     "Fake service that logs everything an intruder tries."),
    (68, "brute-force-simulator", "TOOL", True,
     "Estimate how long a password survives a given attack rate."),
    (69, "secure-note-taking-app", "LIST", True,
     "Notes and saved passwords, encrypted at rest behind one master password."),
    (70, "digital-signature-generator", "TOOL", True,
     "Sign a message with a private key and verify it with the public one."),

    # -- Game Development ---------------------------------------------------
    (71, "snake", "GRID", True,
     "Steer a growing snake around a board without hitting anything."),
    (72, "tetris", "GRID", True,
     "Falling tetrominoes you rotate and drop to clear lines."),
    (73, "memory-matching-game", "GRID", True,
     "Flip cards two at a time and remember where the pairs are."),
    (74, "platformer-2d", "GRID", True,
     "Run and jump across a tile map with gravity and collisions."),
    (75, "chess-engine", "GRID", True,
     "Legal move generation and a minimax search with alpha-beta pruning."),
    (76, "multiplayer-trivia", "GAME", True,
     "Timed questions with several players racing to answer."),
    (77, "space-shooter", "GRID", True,
     "Dodge and shoot waves of descending enemies."),
    (78, "word-scramble", "GAME", True,
     "Unscramble a shuffled word against the clock."),
    (79, "virtual-pet", "GAME", True,
     "Feed, play with and rest a pet whose stats decay over time."),
    (80, "tower-defense", "GRID", True,
     "Place towers along a path and stop waves of creeps."),

    # -- Data Science -------------------------------------------------------
    (81, "covid-data-dashboard", "TOOL", True,
     "Summarise case and vaccination series by region and date."),
    (82, "sales-forecasting", "TOOL", True,
     "Forecast next period from trend and seasonality."),
    (83, "box-office-predictor", "TOOL", True,
     "Predict opening weekend from budget, genre and screen count."),
    (84, "customer-churn-analysis", "TOOL", True,
     "Score which customers are likely to leave and why."),
    (85, "traffic-analysis", "TOOL", True,
     "Aggregate sensor counts into flow, density and congestion."),
    (86, "air-quality-monitor", "TOOL", True,
     "Turn pollutant readings into an AQI band and health advice."),
    (87, "crypto-price-tracker", "LIST", True,
     "Watch a basket of coins and alert on percentage moves."),
    (88, "sports-statistics-analyzer", "TOOL", True,
     "Compute per-game and efficiency stats and rank players."),
    (89, "weather-pattern-predictor", "TOOL", True,
     "Find seasonal patterns in historical weather and extrapolate."),
    (90, "energy-consumption-dashboard", "TOOL", True,
     "Break down usage by appliance and hour, and cost it."),

    # -- Automation and Tools ------------------------------------------------
    (91, "file-organizer", "TOOL", True,
     "Sort a folder into subfolders by type, date or rules."),
    (92, "email-automation-bot", "LIST", True,
     "Queue templated emails and send them on a schedule."),
    (93, "news-web-scraper", "LIST", True,
     "Pull headlines from sources and de-duplicate them."),
    (94, "pdf-merger-splitter", "TOOL", True,
     "Merge PDFs, split by page range and reorder pages."),
    (95, "auto-image-resizer", "TOOL", True,
     "Batch resize to target dimensions while keeping aspect ratio."),
    (96, "invoice-generator", "LIST", True,
     "Build line items into a numbered invoice with tax and totals."),
    (97, "backup-automation", "TOOL", True,
     "Copy a source tree to a destination, skipping unchanged files."),
    (98, "social-post-scheduler", "LIST", True,
     "Queue posts per platform and dispatch them at the right time."),
    (99, "data-cleaning-script", "TOOL", True,
     "Trim, de-duplicate, fix types and fill gaps in a table."),
    (100, "auto-form-filler", "LIST", True,
     "Store field profiles and apply them to a form definition."),

    # -- Creative and Fun ----------------------------------------------------
    (101, "ascii-art-generator", "GRID", True,
     "Turn text into a large ASCII banner using a built-in block font."),
    (102, "meme-generator", "TOOL", False,
     "Lay top and bottom captions over a template image."),
    (103, "music-visualizer", "GRID", False,
     "Animate frequency bands from an audio signal."),
    (104, "random-story-generator", "TOOL", False,
     "Assemble a story from grammar rules and a word bank."),
    (105, "pixel-art-editor", "GRID", False,
     "Paint on a pixel canvas with a palette and export the result."),
    (106, "virtual-art-gallery", "LIST", False,
     "Curate rooms of works with artist, year and description."),
    (107, "interactive-map", "GRID", False,
     "Place and inspect markers on a pannable tile map."),
    (108, "horoscope-app", "TOOL", False,
     "Give a daily reading for a sign worked out from a birth date."),
    (109, "poetry-generator", "TOOL", False,
     "Write verse to a chosen form, counting syllables and rhyme."),
    (110, "animated-greeting-card", "TOOL", False,
     "Build a personalised card with a message and an animation."),

    # -- Community and Social Good --------------------------------------------
    (111, "volunteer-matching", "LIST", False,
     "Match volunteers to opportunities by skill and availability."),
    (112, "donation-tracker", "LIST", False,
     "Track donations against a goal and thank donors."),
    (113, "disaster-relief-coordination", "LIST", False,
     "Report incidents, match needs to offers by location and urgency, and track recovery."),
    (114, "blood-donation-finder", "LIST", True,
     "Find compatible donors and drives near a location."),
    (115, "food-waste-reduction", "LIST", False,
     "Surface surplus food before it expires and route it to takers."),
    (116, "accessibility-checker", "TOOL", True,
     "Audit markup for contrast, alt text, labels and heading order."),
    (117, "mental-health-support-chatbot", "LIST", False,
     "Reflective prompts, grounding exercises and signposting to real help."),
    (118, "public-transport-tracker", "LIST", False,
     "Next departures for a stop with delays and alerts."),
    (119, "missing-persons-database", "LIST", False,
     "Searchable records with descriptions, last seen and case status."),
    (120, "community-garden-planner", "GRID", False,
     "Lay out plots and plan what goes in each bed by season."),

    # -- Advanced and Experimental ---------------------------------------------
    (121, "blockchain-voting", "LIST", True,
     "Cast votes into a hash-linked chain that can be independently verified."),
    (122, "decentralized-file-storage", "LIST", True,
     "Shard a file across nodes with redundancy and content addressing."),
    (123, "iot-home-automation", "LIST", False,
     "Devices, sensor readings and rules that act on them."),
    (124, "drone-control-interface", "GRID", False,
     "Plan a waypoint mission and watch telemetry against it."),
    (125, "ar-navigation", "TOOL", False,
     "Turn a route into bearing and distance cues for an AR overlay."),
    (126, "vr-museum-tour", "LIST", False,
     "Rooms, exhibits and a guided path through a virtual museum."),
    (127, "ai-code-reviewer", "TOOL", False,
     "Flag smells, risky patterns and style problems in a snippet."),
    (128, "smart-traffic-light", "GRID", False,
     "Simulate a junction: lights, routes and signal timing that adapts to the queues waiting."),

    # -- Core Java and Games ---------------------------------------------------
    (129, "number-guessing-game", "GAME", False,
     "Guess a hidden number in a range, with higher or lower feedback and limited attempts."),
    (130, "tic-tac-toe", "GAME", True,
     "Noughts and crosses against a friend or an unbeatable minimax computer."),
    (131, "word-counter", "TOOL", True,
     "Count words, characters, sentences, paragraphs and reading time in a block of text."),
    (132, "text-based-adventure", "GAME", False,
     "Navigate rooms by typing commands, carrying an inventory and saving progress."),
    (133, "simple-banking-app", "LIST", False,
     "Open accounts and make deposits, withdrawals and balance enquiries with a transaction log."),
    (134, "scientific-calculator", "TOOL", False,
     "Trigonometry, logarithms, roots and powers on top of the usual arithmetic."),
    (135, "text-editor", "TOOL", False,
     "Open, edit and save text files with cut, copy, paste and undo."),
    (136, "brick-breaker", "GRID", False,
     "Bounce a ball off a paddle to clear a wall of bricks, tracking score and lives."),
    (137, "flappy-bird", "GRID", False,
     "Tap to keep a bird airborne through gaps in scrolling pipes."),
    (138, "color-hunt-game", "GAME", False,
     "Name the colour a word is printed in, not the word itself, against the clock."),
    (139, "digital-steganography", "TOOL", False,
     "Hide a message in the low bits of an image and pull it back out again."),

    # -- School and Campus Systems ---------------------------------------------
    (140, "attendance-management", "LIST", False,
     "Record attendance per session and report totals and percentages per person."),
    (141, "library-management", "LIST", False,
     "Issue and return books, track due dates and calculate overdue fines."),
    (142, "grading-system", "LIST", False,
     "Enter marks per subject, then compute averages, grades and class rank."),
    (143, "school-management", "LIST", False,
     "Records for students, teachers and staff with role-based views."),
    (144, "cgpa-calculator", "TOOL", False,
     "Turn per-semester credits and grades into an SGPA and a cumulative CGPA."),
    (145, "exam-seating-arrangement", "GRID", False,
     "Lay students out across halls so no two from the same subject sit adjacent."),

    # -- Business and Records Systems ------------------------------------------
    (146, "atm-simulation", "LIST", False,
     "PIN entry, then deposits, withdrawals with note breakdown, and a statement."),
    (147, "pharmacy-management", "LIST", False,
     "Stock, expiry dates and dispensing, flagging medicines that are running out."),
    (148, "supermarket-billing", "LIST", False,
     "Scan items into a basket and produce an itemised bill with tax and discounts."),
    (149, "supply-chain-management", "LIST", False,
     "Track inventory and orders from supplier to customer with stock levels."),
    (150, "helpdesk-management", "LIST", False,
     "Raise tickets, assign them, track status and measure time to resolution."),
    (151, "online-quiz-management", "LIST", False,
     "Build quizzes, sit them under a time limit and review the marked answers."),
    (152, "crime-records-management", "LIST", False,
     "File reports and complaints, link them to cases and search the record."),
    (153, "criminal-face-detection", "TOOL", False,
     "Match a face against a database of records and return the closest candidates."),
    (154, "bug-tracking-system", "LIST", False,
     "Log defects with severity and status, assign them and follow them to closure."),
    (155, "customer-relationship-manager", "LIST", False,
     "Customers, the interactions you have had with them, and the deals in flight."),
    (156, "id-card-generator", "TOOL", False,
     "Turn a person's details into a printable ID card with a photo and barcode."),
    (157, "cv-resume-builder", "TOOL", False,
     "Collect career details and lay them out into a formatted, exportable CV."),

    # -- Travel, City and Communication ----------------------------------------
    (158, "airline-reservation", "LIST", False,
     "Search flights, pick seats, book and cancel, with live seat availability."),
    (159, "smart-city-guide", "LIST", False,
     "Hotels, restaurants and attractions for a city, searchable by category."),
    (160, "online-cab-booking", "LIST", False,
     "Book a cab between two points with fare and arrival estimates and trip status."),
    (161, "simple-search-engine", "TOOL", False,
     "Index documents and rank results for a query by term frequency."),
    (162, "social-networking-site", "LIST", False,
     "Profiles, posts, follows and a timeline assembled from who you follow."),
    (163, "email-system", "LIST", False,
     "Compose, send, receive and thread messages into folders."),
    (164, "office-vpn", "TOOL", False,
     "Tunnel traffic between two hosts over an encrypted socket connection."),

    # -- Twisty Puzzles ---------------------------------------------------------
    # 165-173 share the NxN move engine in lib/com/randomjava/cube and are
    # hand-written, so the generator leaves them alone (see HANDWRITTEN).
    (165, "rubiks-cube-3x3", "GRID", True,
     "Scramble it, solve it with every move explained, ask for one hint, or type in your own cube."),
    (166, "pocket-cube-2x2", "GRID", True,
     "Solved in the fewest turns possible, by measuring the whole puzzle and walking downhill."),
    (167, "revenge-cube-4x4", "GRID", True,
     "Four layers: pair the centres and the edges, then finish it as a 3x3."),
    (168, "professor-cube-5x5", "GRID", True,
     "Five layers, with a fixed centre again but three-piece edges to build."),
    (169, "v-cube-6x6", "GRID", True,
     "Six layers. Reduction on a bigger scale, with inner slices and parity to handle."),
    (170, "v-cube-7x7", "GRID", True,
     "Seven layers, the largest mass-produced cube, solved by the same reduction idea."),
    (171, "void-cube", "GRID", True,
     "A 3x3 with the centres removed, so there is no fixed frame to solve against."),
    (172, "mirror-cube", "GRID", True,
     "A 3x3 in one colour where the pieces are different sizes, so shape is the only clue."),
    (173, "axis-cube", "GRID", True,
     "A 3x3 cut at an angle, so turning it changes its shape entirely before it comes back."),
    (174, "pyraminx", "GRID", False,
     "A tetrahedron with four trivial tips and only four real turning axes."),
    (175, "skewb", "GRID", False,
     "Turns on its corners rather than its faces, cutting the cube along diagonals."),
    (176, "megaminx", "GRID", False,
     "A dodecahedron: twelve faces, fifty pieces, solved layer by layer like a 3x3."),
    (177, "square-1", "GRID", False,
     "Changes shape as it turns, so the first job is getting it back to a cube."),
    (178, "rubiks-clock", "GRID", False,
     "Nine dials on each side, driven by four pins. No twisting at all, pure logic."),
    (179, "pyramorphix", "GRID", True,
     "A 2x2 in a tetrahedron shell, so it deforms as you turn it."),
    (180, "gear-cube", "GRID", False,
     "Every turn drives gears that rotate the edges, so faces only move in half turns."),
    (181, "dino-cube", "GRID", False,
     "Twelve edge pieces turning around the corners. No corners or centres to worry about."),
    (182, "floppy-cube", "GRID", False,
     "A single 1x3x3 layer. Small enough that every position can be listed exhaustively."),

    # -- Cube Solving Methods ----------------------------------------------------
    (183, "cfop-trainer", "LIST", True,
     "Drill the last-layer cases: recognise the pattern, recall the algorithm."),
    (184, "method-comparison", "TOOL", True,
     "Run layer-by-layer and CFOP on the same scramble and compare the move counts."),
    (185, "speedcube-timer", "LIST", True,
     "Inspection countdown, timing, and rolling averages of 5 and 12 over a session."),

    # -- Big Cubes --------------------------------------------------------------
    # All N x N, sharing the generic engine. 1x1 and 2x2 and 3x3 solve;
    # 4x4 and up turn and scramble but await the reduction solver.
    (186, "cube-1x1x1", "GRID", True,
     "A single cubie with nothing to turn, so it is solved the moment you pick it up."),
    (187, "cube-8x8x8", "GRID", True,
     "Eight layers. Past the official limit, and heavy enough to be awkward."),
    (188, "cube-9x9x9", "GRID", True,
     "Nine layers, the first odd cube beyond official competition sizes."),
    (189, "cube-10x10x10", "GRID", True,
     "Ten layers, where lockups start to matter as much as method."),
    (190, "cube-11x11x11", "GRID", True,
     "Eleven layers. Often demonstrated rather than raced."),
    (191, "cube-12x12x12", "GRID", True,
     "Twelve layers of reduction before a 3x3 is left underneath."),
    (192, "cube-13x13x13", "GRID", True,
     "Thirteen layers, near the mechanical limit of the classic design."),
    (193, "cube-14x14x14", "GRID", True,
     "Fourteen layers, a collector's cube more than a solver's."),
    (194, "cube-15x15x15", "GRID", True,
     "Fifteen layers, with well over a thousand stickers to track."),
    (195, "cube-16x16x16", "GRID", True,
     "Sixteen layers, even-numbered so parity comes with it."),
    (196, "cube-17x17x17", "GRID", True,
     "Seventeen layers. The Over The Top cube, long the largest made."),
    (197, "cube-19x19x19", "GRID", True,
     "Nineteen layers, deep into exhibition territory."),
    (198, "cube-21x21x21", "GRID", True,
     "Twenty-one layers, frequently cited as the largest you can buy."),
    (199, "cube-22x22x22", "GRID", True,
     "Twenty-two layers, firmly experimental."),
    (200, "cube-23x23x23", "GRID", True,
     "Twenty-three layers, with centres that take longer than most whole solves."),
    (201, "cube-25x25x25", "GRID", True,
     "Twenty-five layers, 3,750 stickers of reduction."),
    (202, "cube-28x28x28", "GRID", True,
     "Twenty-eight layers, an even cube at experimental scale."),
    (203, "cube-29x29x29", "GRID", True,
     "Twenty-nine layers of patience."),
    (204, "cube-33x33x33", "GRID", True,
     "Thirty-three layers. Gregoire Pfennig's build, over 6,000 pieces."),
    (205, "cube-34x34x34", "GRID", True,
     "Thirty-four layers, beyond any practical solve."),
    (206, "cube-35x35x35", "GRID", True,
     "Thirty-five layers, mostly a demonstration that it can exist."),
    (207, "cube-49x49x49", "GRID", True,
     "Forty-nine layers. Preston Alden's build, 13,839 pieces and 65 pounds."),
    (208, "cube-100x100x100", "GRID", True,
     "One hundred layers and 60,000 stickers, the largest cube ever built."),

    # -- Shape Modifications -----------------------------------------------------
    # Mechanically a 3x3 or a 2x2 underneath, so the existing solvers apply.
    (209, "fisher-cube", "GRID", True,
     "A 3x3 turned 45 degrees about one axis, so edges and centres swap roles."),
    (210, "windmill-cube", "GRID", True,
     "A 3x3 with the middle layer tilted, giving it a windmill silhouette."),
    (211, "ghost-cube", "GRID", True,
     "A 3x3 where no two pieces are alike, so only shape tells you anything."),
    (212, "mastermorphix", "GRID", True,
     "A 3x3 reshaped into a tetrahedron, with centres that visibly rotate."),
    (213, "bandaged-cube", "GRID", True,
     "A 3x3 with pieces glued together, so many turns are simply blocked."),
    (214, "dreidel-cube", "GRID", True,
     "A 3x3 with extra corner cuts, shaped like a spinning top."),
    (215, "x-cube", "GRID", True,
     "A 3x3 with X-shaped cuts that extend past the faces."),
    (216, "bump-cube", "GRID", True,
     "A mirror cube by another name: one colour, pieces of differing height."),
    (217, "camouflage-cube", "GRID", True,
     "A 3x3 with offset layers, so a solved cube looks scrambled."),
    (218, "truncated-cube", "GRID", True,
     "A 3x3 with its corners sliced off, changing the look and nothing else."),
    (219, "cylindrical-cube", "GRID", True,
     "A 3x3 turned into a cylinder. The gentlest shape mod there is."),
    (220, "windmill-morphix", "GRID", True,
     "A windmill cube and a mastermorphix crossed, shifting shape twice over."),
    (221, "junior-cube", "GRID", True,
     "A 2x2 sold for children. Corners only, and every state within eleven turns."),

    # -- Logic and Puzzle Games ---------------------------------------------------
    (222, "tower-of-hanoi", "GRID", True,
     "Move a stack of discs between three pegs, never putting a larger disc on a smaller."),
    (223, "n-queens", "GRID", True,
     "Place N queens on a board so that no two of them attack each other."),
    (224, "sliding-15-puzzle", "GRID", True,
     "Slide numbered tiles into order through the one empty square."),
    (225, "minesweeper", "GRID", True,
     "Clear a grid without detonating a mine, using the counts as clues."),
    (226, "game-2048", "GRID", True,
     "Slide and merge matching tiles, doubling each time, to reach 2048."),
    (227, "sokoban", "GRID", True,
     "Push crates onto targets in a warehouse, never pulling and never squeezing past."),
    (228, "nonogram", "GRID", True,
     "Fill a grid from the run lengths written along each row and column."),
    (229, "lights-out", "GRID", True,
     "Turn every light off, where pressing one flips it and its neighbours."),
    (230, "peg-solitaire", "GRID", True,
     "Jump pegs over each other to leave a single peg in the centre."),
    (231, "mastermind", "GAME", True,
     "Deduce a hidden colour code from black and white peg feedback."),
    (232, "kakuro", "GRID", True,
     "A crossword with sums: fill runs of digits that add to the given totals."),
    (233, "futoshiki", "GRID", True,
     "A Latin square with greater-than signs constraining neighbouring cells."),
    (234, "kenken", "GRID", True,
     "A Latin square where outlined cages must reach a target by one operation."),
    (235, "slitherlink", "GRID", True,
     "Draw a single closed loop so each number has that many edges around it."),
    (236, "hashiwokakero", "GRID", True,
     "Join islands with bridges so every island has its count and all connect."),
    (237, "nurikabe", "GRID", True,
     "Divide a grid into numbered islands separated by one connected wall."),
    (238, "hitori", "GRID", True,
     "Black out cells so no number repeats in a line and the rest stay joined."),
    (239, "binary-puzzle", "GRID", True,
     "Fill a grid with two symbols, never three in a row, balanced and all rows distinct."),
    (240, "skyscrapers", "GRID", True,
     "Place building heights so each edge clue counts the skyline visible from it."),
    (241, "shikaku", "GRID", True,
     "Cut a grid into rectangles, each containing one number equal to its area."),
    (242, "magic-square", "GRID", True,
     "Arrange numbers so every row, column and diagonal adds to the same total."),
    (243, "cryptarithm", "TOOL", True,
     "Solve puzzles like SEND + MORE = MONEY by assigning a digit to each letter."),
    (244, "zebra-puzzle", "TOOL", False,
     "Work out who owns the zebra from a list of constraints, by elimination."),
    (245, "river-crossing", "GRID", True,
     "Get everyone across without leaving the wrong pair alone together."),
    (246, "water-jug", "TOOL", True,
     "Measure an exact amount using jugs that have no markings."),
    (247, "rush-hour", "GRID", False,
     "Slide blocking cars aside to drive the red car out of the jam."),
    (248, "knights-tour", "GRID", True,
     "Move a knight to every square on the board exactly once."),
    (249, "word-search-generator", "GRID", True,
     "Hide a word list in a grid of letters, then solve it back."),
    (250, "tangram", "GRID", False,
     "Fit seven flat shapes together to match a silhouette exactly."),
    (251, "mate-in-n", "GRID", False,
     "Search a chess position for a forced checkmate in a given number of moves."),
]

# Projects whose Java is written by hand and must never be overwritten by the
# generator, even while their solver is still unfinished.
HANDWRITTEN = {"mastermind", "sokoban", "lights-out", "game-2048", "sliding-15-puzzle", "minesweeper", "decentralized-file-storage", "multiplayer-trivia", "blockchain-voting", "blood-donation-finder", "platformer-2d", "chess-engine", "tower-defense", "space-shooter", "virtual-pet", "memory-matching-game", "word-scramble", "snake", "tetris", "port-scanner", "encrypted-chat-app", "keylogger-detector", "secure-file-transfer", "honeypot-server", "digital-signature-generator", "secure-note-taking-app", "image-caption-generator", "voice-command-assistant", "handwritten-digit-recognizer", "stock-price-predictor", "faq-chatbot", "resume-screener", 
    "spam-email-classifier", "movie-recommendation-system",
    "covid-data-dashboard", "box-office-predictor",
    "pdf-merger-splitter", "auto-form-filler",
    "weather-pattern-predictor", "email-automation-bot",
    "news-web-scraper", "social-post-scheduler",
    "crypto-price-tracker", "customer-churn-analysis",
    "traffic-analysis", "invoice-generator",
    "auto-image-resizer", "backup-automation",
    "energy-consumption-dashboard", "sports-statistics-analyzer",
    "brute-force-simulator", "data-cleaning-script",
    "two-factor-authentication", "accessibility-checker", "air-quality-monitor", "sales-forecasting",
    "digital-clock", "currency-converter", "random-quote-generator", "countdown-timer", "anagram-finder", "knapsack-solver", "url-shortener", "expense-tracker", "sentiment-analysis-tool", "file-organizer",
    "tower-of-hanoi", "n-queens",
    "rubiks-cube-3x3", "pocket-cube-2x2", "revenge-cube-4x4", "professor-cube-5x5",
    "v-cube-6x6", "v-cube-7x7", "void-cube", "mirror-cube", "axis-cube",
    "cube-1x1x1", "cube-8x8x8", "cube-9x9x9", "cube-10x10x10",
    "cube-11x11x11", "cube-12x12x12", "cube-13x13x13", "cube-14x14x14",
    "cube-15x15x15", "cube-16x16x16", "cube-17x17x17", "cube-19x19x19",
    "cube-21x21x21", "cube-22x22x22", "cube-23x23x23", "cube-25x25x25",
    "cube-28x28x28", "cube-29x29x29", "cube-33x33x33", "cube-34x34x34",
    "cube-35x35x35", "cube-49x49x49", "cube-100x100x100", "fisher-cube",
    "windmill-cube", "ghost-cube", "mastermorphix", "bandaged-cube",
    "dreidel-cube", "x-cube", "bump-cube", "camouflage-cube",
    "truncated-cube", "cylindrical-cube", "windmill-morphix", "junior-cube",
    "pyramorphix", "cfop-trainer", "method-comparison", "speedcube-timer",
}


def category_for(project_id: int) -> str:
    for low, high, name in CATEGORIES:
        if low <= project_id <= high:
            return name
    raise ValueError(f"no category covers id {project_id}")


# Titles no rule can derive from a slug. A hyphen in the slug is a word
# separator everywhere except where it is part of the name, and the deriver has
# no way to tell those apart.
NAME_OVERRIDES = {
    "tic-tac-toe": "Tic-Tac-Toe",
    "secure-note-taking-app": "Secure Note-Taking App",
    "note-taking-app": "Note-Taking App",
}


def title_for(slug: str) -> str:
    """Human title from a slug, with a few acronyms and names fixed up."""
    if slug in NAME_OVERRIDES:
        return NAME_OVERRIDES[slug]
    special = {
        "bmi": "BMI", "html": "HTML", "qr": "QR", "cms": "CMS", "url": "URL",
        "ai": "AI", "faq": "FAQ", "cv": "CV", "2d": "2D", "pdf": "PDF",
        "cfop": "CFOP", "oll": "OLL", "pll": "PLL", "nxn": "NxN",
        "ascii": "ASCII", "vr": "VR", "ar": "AR", "iot": "IoT",
        "e": "E", "todo": "To-Do", "cgpa": "CGPA", "atm": "ATM",
        "id": "ID", "vpn": "VPN", "app": "App",
    }
    words = []
    for word in slug.split("-"):
        words.append(special.get(word, word.capitalize()))
    return " ".join(words)


def package_for(slug: str) -> str:
    return "".join(ch for ch in slug if ch.isalnum()).lower()


def class_for(slug: str) -> str:
    return "".join(word.capitalize() for word in slug.split("-") if word)


def rows():
    """Yields a dict per project with everything the generator needs."""
    seen_ids, seen_slugs = set(), set()
    for project_id, slug, kind, done, description in PROJECTS:
        if project_id in seen_ids:
            raise ValueError(f"duplicate id {project_id}")
        if slug in seen_slugs:
            raise ValueError(f"duplicate slug {slug}")
        seen_ids.add(project_id)
        seen_slugs.add(slug)
        category = category_for(project_id)
        difficulty = DIFFICULTY_OVERRIDES.get(
            project_id, CATEGORY_DIFFICULTY.get(category, "intermediate"))
        if difficulty not in ("beginner", "intermediate", "advanced"):
            raise ValueError(f"bad difficulty {difficulty!r} for id {project_id}")
        yield {
            "id": project_id,
            "slug": slug,
            "name": title_for(slug),
            "category": category,
            "kind": kind,
            "difficulty": difficulty,
            "done": done,
            "description": description,
            "stack": STACKS.get(project_id, ""),
            "package": package_for(slug),
            "klass": class_for(slug),
            "folder": f"{project_id:03d}-{slug}",
        }
